@startmindmap


*  <b>Diagnostic Workflow</b>
** Order Managment (LAB-1 and LAB-2)
*** [[StructureDefinition-ServiceRequest.html Service Request (ORC)]]
** Order Results Management (LAB-3)
*** [[StructureDefinition-DiagnosticReport.html Diagnostic Report (OBR)]]
** Sample Management\nSpecimen Event Tracking
*** [[StructureDefinition-Specimen.html Specimen (SPM)]]
** [[StructureDefinition-Task.html Task (Future)]]
* Patient Administration
** [[StructureDefinition-Patient.html Patient (PID)]]
** [[StructureDefinition-HospitalSpell.html Encounter/Hospital Spell  (PV1)]]
** Care Directory
*** [[StructureDefinition-Organization.html Organisation]]
*** [[StructureDefinition-Practitioner.html Practitioner]]
* Health Documents
** [[StructureDefinition-DocumentReference.html Document Reference (OBX and XDS Document Entry)]]

@endmindmap
