@startmindmap

title "Somatic Reporting"

* [[StructureDefinition-DiagnosticReport.html Genomic Report]] (Somatic)
** [[StructureDefinition-Patient.html patient (subject)]]
** [[StructureDefinition-ServiceRequest.html Order (basedOn)]]
** [[StructureDefinition-Specimen.html specimen]]
** Results Interpreter
** Performer
** results
*** [[https://hl7.org/fhir/uv/genomics-reporting/StructureDefinition-variant.html Variant]]
**** [[https://hl7.org/fhir/uv/genomics-reporting/StructureDefinition-diagnostic-implication.html Diagnostic Implication]]
** presentedFrom
*** [[StructureDefinition-NWAttachment.html Attachment]] (report in PDF format)

@endmindmap
