@startmindmap

title "Somatic Reporting"

* [[StructureDefinition-DiagnosticReport.html Genomic Report]] (Somatic)
** [[StructureDefinition-Patient.html Patient (subject)]]
** [[StructureDefinition-ServiceRequest.html Order (basedOn)]]
** [[StructureDefinition-Specimen.html Specimen]]
** Results Interpreter
** Performer
** results
*** [[StructureDefinition-Variant.html Variant]]
**** [[StructureDefinition-DiagnosticImplication.html Diagnostic Implication]]
** presentedFrom
*** [[StructureDefinition-NWAttachment.html Attachment]] (report in PDF format)

@endmindmap
