@startuml

title "Patient Identity Feed"

agent "Patient Identity Source" as Source

agent "Patient Identifier Cross-reference Manager" as MPI


Source -r-> MPI: [[https://profiles.ihe.net/ITI/TF/Volume2/ITI-8.html Patient Identity Feed (ITI-8)]]\n[[https://profiles.ihe.net/ITI/PIXm/ITI-104.html Patient Identity Feed FHIR (ITI-104)]]

@enduml
