@startuml

title "Publish a Document"

agent "Document Source" as Source
node "Document Recipient" as Filler {
agent "Document Registry" as Registry
agent "Document Repository" as Repository
Registry -d[hidden]- Repository
}


Source -r-> Filler: [[https://profiles.ihe.net/ITI/TF/Volume2/ITI-41.html Provide and Register Document Set-b (ITI-41)]]\n[[https://profiles.ihe.net/ITI/MHD/ITI-65.html Provide Document Bundle (ITI-65)]]\n[[https://profiles.ihe.net/ITI/MHD/ITI-105.html Simplified Publish (ITI-105)]]\n[[https://profiles.ihe.net/ITI/MHD/ITI-106.html Generate Metadata (ITI-106)]]


@enduml
