@startmindmap

title "Genomic Laboratory Report"

* [[StructureDefinition-DiagnosticReport.html Diagnostic Report]]
** Patient Demographics
*** Identification [[StructureDefinition-NHSIdentifier.html NHS Identifier]]
*** Identification [[StructureDefinition-MedicalRecordNumber.html Medical Record Number]]
*** Name, date of birth, post code, etc.
** Hospital Spell
*** Case identification / Account Number [[StructureDefinition-HospitalProviderSpellIdentifier.html Hospital Provider Spell Identifier]]
*** Service Type [[ValueSet-service.html Service]]
** [[Questionnaire-GenomicTestOrder.html Order Details]]
*** [[StructureDefinition-OrderIdentifier.html Order Identifier (Placer)]]
*** Filler Order Number
*** Ordering Facility [[StructureDefinition-OrganisationCode.html Organisation Code]]
*** Reason Code
**** Gene disease assessed [[CodeSystem-GenomicClinicalIndication.html Clinical Indication]]
*** [[https://www.datadictionary.nhs.uk/data_elements/local_treatment_category_code.html (Order) Procedure Code]]
**** Genomic Test Code [[CodeSystem-GenomicTestCode.html Test Directory Code]]
*** [[StructureDefinition-Specimen.html Specimen]]
**** Accession Number
** Test Details
*** [[StructureDefinition-ReportIdentifier.html Report Identifier]]
*** Performer
*** Results Interpreter
** Conclusion (related to Gene disease assessed)
** NHS England Genomics Test Outcome
** Genomic Analysis Narrative Report (PDF) [[StructureDefinition-NWAttachment.html Attachment]]
** [[StructureDefinition-Observation.html Results (Observations]]
*** [[#laboratory-analyte-result Laboratory Analyte Result]]
*** Finding
**** [[#reportable-variant Variant]]
*** Implication
**** [[#diagnostic-implication Diagnostic Implication]]
**** [[#implications Therapeutic Implication]]
** [[#genomic-study Genomic Study/Method]]
*** Analysis method [Type]
*** [[#genomic-study-analysis Genomic Study Analysis]]
**** Regions Studied / Gene mutations tested

@endmindmap
