@startmindmap

title "Genomic Laboratory Order"

* [[StructureDefinition-ServiceRequest.htmlLaboratory Test Order]]
** [[StructureDefinition-Patient.html Patient (subject)]]
** Healthcare Professional
** Clinical Indication (Condition)
** Account Number (Episode or Stay Number)
** Test Directory Code
** [[StructureDefinition-Specimen.html Specimen]]
** Supporting Information
*** Test Request
**** Consent
*** Patient Clinical Information
*** Ask At Order Entry
**** Pregnant
*** Prior Results

@endmindmap
