@startuml

hide footbox

participant "Order Placer" as EPR
participant "Enterprise Document\n Sharing" as XDS
participant "Enterprise Data\nSharing\n(FHIR Repository)" as CDR
participant "Intermediary\nRegional Integration Engine (RIE)" as TIE
participant "Order Filler" as LIMS



== Submit Test Order Form ==

alt IHE LTW Workflow
EPR -> TIE: \nSend HL7 FHIR Message\n**Laboratory Order O21**
end
TIE -> LIMS: Send HL7 v2 Message\n**ORML_O01**
TIE -> CDR: HL7 FHIR REST (internal)

== Perform Test ==

LIMS -> LIMS: Perform Test

== Send Genomic Report ==

LIMS -> TIE: Send HL7 v2 Message\n**ORU_R01**
alt IHE LTW Workflow
TIE -> EPR: Send HL7 v2 Message\n**ORU_R01**
end
alt IHE LTW Workflow
TIE -> XDS: Send HL7 v2 Message\n**ORU_R01**
end
TIE -> CDR: HL7 FHIR REST (internal)

@enduml
