@startuml

hide footbox

title "Event Notifications and Enterprise Shared Data/Document Repositories Option"

participant "Order Placer" as EPR
participant "Intermediary\nRegional Integration Engine (RIE)" as TIE
participant "Enterprise Document/Data Sharing" as CDR
participant "Order Filler" as LIMS


EPR -> EPR: Complete Referral Form
EPR -> TIE: [[LAB-1.html Placer Order Managment (LAB-1)]] [[DDD-TestOrder.html Genomic Order O21]] Command Message
TIE -> LIMS: [[LAB-1.html Placer Order Managment (LAB-1)]] [[DDD-TestOrder.html Genomic Order O21]] Document Message
TIE -> CDR: [[LAB-1.html Placer Order Managment (LAB-1)]] [[DDD-TestOrder.html Genomic Order O21]] Command Message
TIE -> CDR: [[StructureDefinition-Task.html FHIR Task]] (accepted) Event Message
alt Order Placer can choose to start supporting FHIR Workflow
TIE -> EPR: [[StructureDefinition-Task.html FHIR Task]] (accepted) Event Message
end
LIMS -> LIMS: Perform Test

LIMS -> TIE: [[LAB-3.html Order Results Management (LAB-3)]] [[DDD-TestReport.html Genomic Report R01]] Document Message
TIE -> CDR: [[StructureDefinition-Task.html FHIR Task]] (completed) Event Message
alt Order Placer can choose to start supporting FHIR Workflow
TIE -> EPR: [[StructureDefinition-Task.html FHIR Task]] (completed) Event Message
opt when required
  EPR -> TIE: Retrieve [[LAB-3.html Order Results Management (LAB-3)]] [[DDD-TestReport.html Genomic Report R01]] Document Message
end
else Traditional Messaging
TIE -> EPR: [[LAB-3.html Order Results Management (LAB-3)]] [[DDD-TestReport.html Genomic Report R01]] Document Message
end


@enduml
