@startuml

skinparam svgDimensionStyle false

title "Shared Repositories and FHIR Workflow Option"

hide footbox

participant "Order Placer" as EPR
participant "Order Placer Repository" as CDRO
participant "Order Filler Repository" as CDRF
participant "Order Filler" as LIMS


EPR -> EPR: Complete Referral Form
EPR -> CDRO: [[LAB-1.html Placer Order Managment (LAB-1)]] [[DDD-TestOrder.html Genomic Order O21]] Document Message
EPR -> LIMS: [[StructureDefinition-Task.html FHIR Task]] (requested) Event Message
LIMS -> CDRO: Retrieve [[LAB-1.html Placer Order Managment (LAB-1)]] [[DDD-TestOrder.html Genomic Order O21]] REST API
LIMS -> EPR: [[StructureDefinition-Task.html FHIR Task]] (accepted) Event Message


LIMS -> LIMS: Perform Test

LIMS -> CDRF: [[LAB-3.html Order Results Management (LAB-3)]] [[DDD-TestReport.html Genomic Report R01]] Document Message
LIMS -> EPR: [[StructureDefinition-Task.html FHIR Task]] (completed) Event Message
EPR -> CDRF: Retrieve [[LAB-3.html Order Results Management (LAB-3)]] [[DDD-TestReport.html Genomic Report R01]] Document Message

@enduml
