@startuml

title "IHE LTW Actor Diagram"

agent "Order Placer" as Placer
agent "Order Filler" as Filler
agent "Automation Manager" as Manager
agent "Order Result Tracker" as Tracker

Placer -r-> Filler: [[LAB-1.html Placer Order Management (LAB-1)]]
Filler -l-> Placer: [[LAB-2.html Filler Order Management (LAB-2)]]

Filler -u-> Tracker: [[LAB-3.html Order Results Management (LAB-3)]]
Filler -d-> Manager: [[LAB-4.html Work Order Management (LAB-4)]]
Manager -u-> Filler: Test Results Management (LAB-5)

@enduml
