@startuml

skinparam svgDimensionStyle false

title "Multiple Clinical Data Repositories and FHIR Workflow"

hide footbox

participant "Order Placer" as EPR
participant "Order Placer\nClinical Data Repository" as CDRO
participant "Order Filler\nClinical Data Repository" as CDRF
participant "Order Filler" as LIMS


EPR -> EPR: Complete Order Form
EPR -> CDRO: Store Genomic Order
EPR -> LIMS: [[StructureDefinition-Task.html FHIR Task]] (requested) Event Message
LIMS -> CDRO: Retrieve Genomic Order FHIR REST API

alt accepted
LIMS -> EPR: [[StructureDefinition-Task.html FHIR Task]] (accepted) Event Message

LIMS -> LIMS: Perform Test
opt partial/preliminary reports
LIMS -> LIMS: Create preliminary/partial report

LIMS -> CDRF: Store partial/preliminary Genomic Report
LIMS -> EPR: [[StructureDefinition-Task.html FHIR Task]] (in-progress) Event Message
EPR -> CDRF: Retrieve Genomic Report FHIR REST API
end
LIMS -> LIMS: Create final report

LIMS -> CDRF: Store partial/preliminary Genomic Report
LIMS -> EPR: [[StructureDefinition-Task.html FHIR Task]] (completed) Event Message
EPR -> CDRF: Retrieve Genomic Report FHIR REST API

else Rejected
LIMS -> EPR: [[StructureDefinition-Task.html FHIR Task]] (rejected) Event Message
end
@enduml
