  @startuml

  skinparam svgDimensionStyle false

  title "Genomic Test Request"

  frame "Laboratory Order O21" as Message {
  entity "FHIR Bundle (messaage)" as oml <<aggregate>> {
  identifier
  }

  class "[[StructureDefinition-MessageHeader.html MessageHeader]]" as MSH {
   focus
  }

    frame "Template/Order Form" as Composition {
      entity "[[StructureDefinition-Patient.html Patient]]" as PID {
      [[StructureDefinition-NHSNumber.html NHSNumber]]
      [[StructureDefinition-MedicalRecordNumber.html MedicalRecordNumber]]
      }

      entity "[[StructureDefinition-Encounter.html Encounter]]" as PV1 {
      identifier : [[StructureDefinition-VisitNumber.html Visit Number]]
      encounter
      episode
      subject : Patient
      }


      entity "[[StructureDefinition-ServiceRequest.html ServiceRequest]] \n([[https://simplifier.net/guide/fhir-genomics-implementation-guide/Home/Design/Clinicalheadings#Test-Request Test Request]])" as ORC <<aggregate>> {
      orderPlacerNumber
      orderFillerNumber
      orderPlacerGroupNumber
      accessionNumber
      subject : Patient
      }

      entity "[[StructureDefinition-Specimen.html Specimen]] \n([[https://simplifier.net/guide/fhir-genomics-implementation-guide/Home/Design/Clinicalheadings#Primary-Sample Primary Sample]])" as SPM {
      identifier
      accessionNumber
      subject : Patient
      }

      class "ConditionCode" as DG1

      class "[[StructureDefinition-PractitionerRole.html PractitionerRole]]" as STF {
       organisation : ODSCode
       practitioner: GMP/GMC Number
       specialty: ClinicalSpecialty
      }

      class "ServieRequest.identifier \nOriginal Order" as previous {

      }


      frame "Supporting Information" as supportingInfo {



        class "[[StructureDefinition-Observation.html Observation]]" as OBX1 {
        value[x]
        code
        subject : Patient
        }


        class "[[StructureDefinition-Observation-Panel.html Observation Panel]]" as panel {
        hasmember
        code
        subject : Patient
        }

        entity "[[StructureDefinition-DocumentReference.html DocumentReference]]\nPreviousReports\nGenomicFamilyStructure" as documentReference <<aggregate>> {
           type
           subject : Patient
           context.encounter : [[StructureDefinition-VisitNumber.html Visit Number]]
        }

        class "[[StructureDefinition-NWAttachment.html Attachment]]" as attachment {
         contentType
          url
        }

        class "[[StructureDefinition-Binary.html Binary]]" as binary

      }

      documentReference *-d-> attachment

      attachment *-- binary : url

      panel *-d- "0" OBX1: hasmember

      OBX1 -d[hidden]- documentReference

   }
  }

  oml o-d- "1" MSH
  MSH o-d- "1" ORC: focus
  ORC *-- "0" SPM : specimen /\n accessionNumber
  ORC o-- "1" PID : subject
  ORC o-- "0" PV1 : encounter
  ORC *-- "0" DG1 : reason\n(Reference/Code)
  ORC o-- "0" previous: basedOn
  ORC *-- "0" OBX1: supportingInfo
  ORC *-- "0" panel: supportingInfo
  ORC *-- "0" documentReference: supportingInfo
  ORC *-- "1" STF: requester
  SPM o-- "0" STF: collection.collector
  PV1 o-- "0" STF: participant.individual
  PV1 o-- "1" PID : subject
  SPM o-- "1" PID : subject
  documentReference o-- "1" PID : subject
  OBX1 o-- "1" PID : subject

  documentReference o-- "1" PV1 : context.encounter

  OBX1 o-- "1" PV1 : encounter

  @enduml
