@startuml

title "Genomic Test Request (Local)"


frame "Order\n(HL7 v2 OML_O21)"  as Order {

  entity "Patient \n(HL7 v2 PID)" as PID

  note bottom of PID
  HL7 FHIR [[StructureDefinition-Patient.html Patient]]
  end note

  entity "Encounter \n(HL7 v2 PV1)" as PV1

  entity "ServiceRequest\n(HL7 v2 ORC)" as ORC <<aggregate>>

  entity "Specimen \n(HL7 v2 SPM)" as SPM

  note bottom of SPM
  HL7 FHIR [[StructureDefinition-Specimen.html Specimen]]
  openEHR [[https://ckm.openehr.org/ckm/archetypes/1013.1.331 Specimen]]

  end note

  note right of ORC
HL7 FHIR [[StructureDefinition-ServiceRequest.html ServiceRequest]]
openEHR [[https://ckm.openehr.org/ckm/archetypes/1013.1.614 Service request]]
end note

  frame OrderEntryForm {
    entity "Genomic Order Entry Form" as QR <<aggregate>>

    entity "Items\n(Hl7 v2 OBX)" as OBX {
      question
      answer
    }

    note right of QR
    MFT (EPIC and LIMS) [[Questionnaire-NW-Genomics-Test-Order.html Genonics Order Entry Form]]
    (this can be defined as a FHIR Questionnaire
    or openEHR Template?)

    HL7 FHIR [[StructureDefinition-Observation-Panel.html Observation Panel]]
    or HL7 FHIR [[StructureDefinition-QuestionnaireResponse.html QuestionnaireResponse]]
    end note

    note right of OBX
    HL7 FHIR [[StructureDefinition-Observation.html Observation]]
    end note
  }
}


ORC *-- "0..*" SPM : specimen
ORC *-- "1..1" PID : subject
ORC *-- "0..1" PV1 : encounter
ORC *-- "1..1" QR : supportingInfo
QR *-- "1..*" OBX: hasMember

@enduml
