@startuml

title "Genomic Order Component Model"

component "NW Genomic Laboratory Hub (LIMS)" as LIMS
component "Electronic Patient\nRecord (EPR)" as EPR
component "NW GLH Regional Integration Engine (RIE)" as TIE
component "NHS England Genomic Order Management Service" as GOMS

frame "Data Capture" as sdc {
  component "Order Entry\nUser Application" as user
}

frame "Placer Order Management [LAB-1] (to GLH RIE)" as xChange1 {
 interface "HL7 v2.x ORM\n(or FHIR Message)" as HL7_ORM1
}

frame "Placer Order Management [LAB-1] (from GLH RIE)" as xChange2 {
 interface "HL7 v2.x ORM/OML?" as HL7_ORM2
 interface "FHIR Transaction\n(FHIR Workflow)" as Transaction
}

EPR -d-> HL7_ORM1
HL7_ORM1 -d-> TIE
TIE -d-> HL7_ORM2
TIE -d-> Transaction: External orders
Transaction -d-> GOMS

HL7_ORM2 -d-> LIMS
user -d-> LIMS : Manual Order Upload

note left of user
This needs converting to a HL7 interface
to allow orders to flow via the GLH RIE
end note

note right of TIE
Transforms between different formats
Can provide code conversions
Routes orders
end note

@enduml
