@startuml

title "Genomics Order Options"

interface "Genomics Order In" as GenomicsOrderIn
component "GLH TIE" as GLHTIE
interface "Genomics Order Out" as GenomicsOrderOut

GenomicsOrderIn -r-> GLHTIE
GLHTIE -r-> GenomicsOrderOut

note bottom of GenomicsOrderIn
Opt 1 HL7 HL7 v2.x ORM
Opt 2, 3 and 4 HL7 FHIR Message/Transaction
end note


note top of GenomicsOrderOut
Opt 1 ,2 and 3 HL7 HL7 v2.x ORM
Opt 4 HL7 FHIR Transaction
end note

@enduml
