@startuml

title "Query for Clinical Data"

agent "Clinical Data Consumer" as Consumer

agent "Clinical Data Source" as Source

}

Consumer -r-> Source: [[https://profiles.ihe.net/PCC/QEDm/PCC-44.html Mobile Query Existing Data (PCC-44)]]

@enduml
