@startuml

title "Genomic Report Component Model"

component "Laboratory Information\nManagmenet System (LIMS)" as LIMS

component "Electronic Patient\nRecord (EPR)" as EPR

component "Electronic Document\nManagement Systems (EDMS)" as EDMS

component "Trust Integration Engine (TIE)" as TIE
component "NHS England Genomic Order Management Service" as GOMS

interface "HL7 v2.x ORU\n(or FHIR Message)" as HL7_ORU1
interface "HL7 v2.x ORU\n(or FHIR Message)" as HL7_ORU2
interface "FHIR Transaction" as Transaction
interface "IHE XDS ITI-41/MHD ITI-105\n(pdf or FHIR Document)" as MHD105
interface "HL7 IPA\n(FHIR RESTful)" as IPA
interface "IHE XDS ITI-18 & 43\nor MHD ITI-67 & 68\n(pdf or FHIR Document)" as MHD67

interface "HL7 IPA\n(FHIR RESTful)" as IPA2

component "User Application" as user

LIMS -d-> HL7_ORU1
HL7_ORU1 -d-> TIE

TIE -d-> HL7_ORU2 : Option EPR
HL7_ORU2 -d-> EPR

TIE -d-> MHD105 : Option EDMS
MHD105 -d-> EDMS

TIE -d-> Transaction : External EPR/EDMS
Transaction -d-> GOMS
GOMS -d-> IPA2

EDMS -d-> MHD67
EPR -d-> IPA

IPA -d-> user
MHD67 -d-> user
IPA2 -d-> user

note right of TIE
Transforms between different formats
Can provide code conversions
Routes report
end note

@enduml
