@startuml


frame "North West [[LTW.html Genomic Testing Workflow (LTW)]]" as NW {
  agent "Order Placer" as Placer
  agent "Order Filler" as Filler
  agent "Order Result Tracker" as Tracker
}
frame "NHS England Genomic Order Management Service" as  NHSE {
  agent "Automation Manager" as Manager
}
Placer -r-> Filler: [[LAB-1.html Placer Order Management (LAB-1)]]
Filler -l-> Placer: Filler Order Management [LAB-2]

Filler -u-> Tracker: [[LAB-3.html Order Results Management (LAB-3)]]
Filler -d-> Manager: Work Order Management [LAB-4]
Manager -u-> Filler: Test Results Management [LAB-5]

@enduml
