ValueSet: GMSWGSGuideCancerTestCodesVS
Id: GMSWGSGuideCancerTestCodesVS
Title: "GMS WGS Cancer Form - Guide Test Codes"
Description: """
The [Genomic Test Code](CodeSystem-GenomicTestCode.html) (`$GTD`,
`England-GenomicTestDirectory`) `M*` codes whose display text names Whole Genome
Sequencing (WGS) specifically - 214 codes, all Cancer. Same relationship as [GMS WGS
Guide Test Codes](ValueSet-GMSWGSGuideTestCodesVS.html) has to [GMS WGS Rare
Disease](Questionnaire-GMSWGSRareDisease.html): a candidate guide list for [GMS WGS
Cancer](Questionnaire-GMSWGSCancerAskAtOrderEntry.html)'s own Test Directory Clinical
Indication item, which is currently bound to the full
[GenomicTestCodes](ValueSet-GenomicTestCodes.html) ValueSet (every test family, not
just WGS).

Every code follows one of three patterns per cancer type - **WGS Germline and
Tumour**/**Tumor** (both spellings appear in NHS England's own source spreadsheet,
carried through unchanged), **WGS Tumour First**, or **WGS Follow-up Germline** -
reflecting the three-sample-timing WGS pathway (paired germline+tumour together,
tumour-first, or a later germline follow-up) rather than three different tests.
"""
* ^experimental = true

* $GTD#M42.4 "Alveolar Rhabdomyosarcoma, WGS Germline and Tumour"
* $GTD#M43.2 "Alveolar Soft Part Sarcoma, WGS Germline and Tumour"
* $GTD#M45.3 "Angiomatoid Fibrous Histiocytoma, WGS Germline and Tumour"
* $GTD#M46.2 "Chondrosarcoma Conventional Central, WGS Germline and Tumour"
* $GTD#M47.2 "Chondroblastoma, WGS Germline and Tumour"
* $GTD#M48.2 "Clear Cell Sarcoma of Soft Tissue, WGS Germline and Tumour"
* $GTD#M49.2 "CNS Ewing Sarcoma Family Tumour With CIC Alteration, WGS Germline and Tumour"
* $GTD#M50.2 "Dermatofibrosarcoma Protuberans, WGS Germline and Tumour"
* $GTD#M52.2 "Desmoplastic Small Round Cell Tumour, WGS Germline and Tumour"
* $GTD#M53.4 "Endometrial Stromal Sarcoma, WGS Germline and Tumour"
* $GTD#M55.3 "Ewing Like Sarcoma/PNET, WGS Germline and Tumour"
* $GTD#M56.2 "Ewing Sarcoma of Bone, WGS Germline and Tumour"
* $GTD#M57.3 "Ewing-Like Soft-Tissue Sarcoma, WGS Germline and Tumour"
* $GTD#M58.2 "Extraskeletal Myxoid Chondrosarcoma, WGS Germline and Tumour"
* $GTD#M60.2 "Giant Cell Tumour of Bone, WGS Germline and Tumour"
* $GTD#M61.3 "High-Grade Neuroepithelial Tumour-Bcor Group, WGS Germline and Tumour"
* $GTD#M62.2 "Infantile Fibrosarcoma, WGS Germline and Tumour"
* $GTD#M63.4 "Inflammatory Myofibroblastic Tumour, WGS Germline and Tumour"
* $GTD#M64.2 "Low Grade Fibromyxoid Sarcoma, WGS Germline and Tumour"
* $GTD#M65.2 "Mesenchymal Chondrosarcoma, WGS Germline and Tumour"
* $GTD#M66.2 "Myoepithelial Tumours of Soft Tissue, WGS Germline and Tumour"
* $GTD#M67.2 "Myxoid/Round Cell Liposarcoma, WGS Germline and Tumour"
* $GTD#M68.2 "Myxoinflammatory Fibroblastic Sarcoma, WGS Germline and Tumour"
* $GTD#M70.2 "Osteosarcoma, WGS Germline and Tumour"
* $GTD#M71.2 "Phosphaturic Mesenchymal Tumour, WGS Germline and Tumour"
* $GTD#M72.3 "Primitive Mesenchymal Myxoid Tumour of Infancy, WGS Germline and Tumour"
* $GTD#M73.2 "Pseudomyogenic Haemangioendothelioma, WGS Germline and Tumour"
* $GTD#M74.2 "Radiation Induced Angiosarcoma, WGS Germline and Tumour"
* $GTD#M75.3 "Round Cell Sarcoma Nos, WGS Germline and Tumour"
* $GTD#M76.2 "Sclerosing Epithelioid Fibrosarcoma, WGS Germline and Tumour"
* $GTD#M77.2 "Synovial Sarcoma, WGS Germline and Tumour"
* $GTD#M78.2 "Undifferentiated Round Cell Sarcoma of Infancy, WGS Germline and Tumour"
* $GTD#M79.2 "Well Differentiated/Dedifferentiated Liposarcoma, WGS Germline and Tumour"
* $GTD#M119.1 "Paediatric Tumours, WGS Germline and Tumour"
* $GTD#M124.9 "Clear Cell Kidney Sarcoma - Paediatric, WGS Germline and Tumour"
* $GTD#M127.3 "Congenital Mesoblastic Nephroma - Paediatric, WGS Germline and Tumour"
* $GTD#M131.4 "Cystic Nephroma - Paediatric, WGS Germline and Tumour"
* $GTD#M143.4 "Lung - Paediatric, WGS Germline and Tumour"
* $GTD#M149.2 "Melanotic Tumours - Paediatric, WGS Germline and Tumour"
* $GTD#M151.5 "Midline Carcinoma - Paediatric, WGS Germline and Tumour"
* $GTD#M152.14 "Neuroblastoma - Paediatric, WGS Germline and Tumour"
* $GTD#M157.5 "Thyroid Papillary Carcinoma - Paediatric, WGS Germline and Tumour"
* $GTD#M161.4 "Pleuropulmonary Blastoma - Paediatric, WGS Germline and Tumour"
* $GTD#M165.6 "Renal Tumours - Paediatric, WGS Germline and Tumour"
* $GTD#M166.2 "Retinoblastoma - Paediatric, WGS Germline and Tumour"
* $GTD#M167.4 "Rhabdoid Tumours - Paediatric, WGS Germline and Tumour"
* $GTD#M173.2 "t(6;11) Translocation-Associated Renal Cell Carcinoma - Paediatric, WGS Germline and Tumour"
* $GTD#M174.3 "Testicular - Paediatric, WGS Germline and Tumour"
* $GTD#M178.3 "Wilms Tumours - Paediatric, WGS Germline and Tumour"
* $GTD#M180.6 "Xp11.2 Translocation-Associated Renal Cell Carcinoma - Paediatric, WGS Germline and Tumour"
* $GTD#M196.3 "Bone Forming Soft Tissue Tumour Differential, WGS Germline and Tumour"
* $GTD#M197.10 "Round Cell Sarcoma of Soft Tissue Differential, WGS Germline and Tumour"
* $GTD#M198.4 "Vascular Soft Tissue Tumour Differential, WGS Germline and Tumour"
* $GTD#M199.12 "Spindle Cell Soft Tissue Tumour Differential, WGS Germline and Tumour"
* $GTD#M200.7 "Myxoid Soft Tissue Tumour Differential, WGS Germline and Tumour"
* $GTD#M201.3 "Adipocytic Soft Tissue Tumour Differential, WGS Germline and Tumour"
* $GTD#M202.6 "Epithelioid Soft Tissue Tumour Differential, WGS Germline and Tumour"
* $GTD#M203.5 "Uterine Sarcomas (Inc Endometrial), WGS Germline and Tumour"
* $GTD#M204.1 "Undifferentiated tumour, WGS Germline and Tumour"
* $GTD#M205.7 "Cartilage Forming Bone Tumour Differential, WGS Germline and Tumour"
* $GTD#M206.7 "Bone Forming Bone Tumour Differential, WGS Germline and Tumour"
* $GTD#M207.6 "Osteoclast-Rich Bone Tumour Differential, WGS Germline and Tumour"
* $GTD#M208.6 "Round Cell Sarcoma of Bone Differential, WGS Germline and Tumour"
* $GTD#M209.4 "Vascular Tumour of Bone Differential, WGS Germline and Tumour"
* $GTD#M210.5 "Spindle Cell Tumour of Bone Differential, WGS Germline and Tumour"
* $GTD#M211.3 "Fibro-Osseous Tumour of Bone Differential, WGS Germline and Tumour"
* $GTD#M212.14 "Renal Tumour Differential - Paediatric, WGS Germline and Tumour"
* $GTD#M226.4 "Carcinoma of Unknown Primary, WGS Germline and Tumour"
* $GTD#M232.1 "Solid Tumour Exhausted all Standards of Care Testing and Treatment- Adult, WGS Germline and Tumour"
* $GTD#M233.1 "High Grade Ovarian Carcinoma, WGS Germline and Tumour"
* $GTD#M234.1 "Triple Negative Breast Cancer, WGS Germline and Tumour"
* $GTD#M20.3 "Anaplastic Astrocytoma, Paediatric, WGS Germline and Tumor"
* $GTD#M21.22 "Astrocytoma, Adult, WGS Germline and Tumor"
* $GTD#M22.4 "Diffuse Astrocytoma, Paediatric, WGS Germline and Tumor"
* $GTD#M23.12 "Diffuse Midline Glioma, Adult, WGS Germline and Tumor"
* $GTD#M24.3 "Embryonal Tumours with Multi-Layered Rosettes, Paediatric, WGS Germline and Tumor"
* $GTD#M25.6 "Ependymoma, Paediatric, WGS Germline and Tumor"
* $GTD#M26.5 "Ependymoma, Adult, WGS Germline and Tumor"
* $GTD#M27.16 "Glioblastoma, Adult, WGS Germline and Tumor"
* $GTD#M28.9 "Glioma, Adult, WGS Germline and Tumor"
* $GTD#M29.9 "High Grade Glioma, Adult, WGS Germline and Tumor"
* $GTD#M30.2 "IDH-Wildtype Glioblastoma, Paediatric, WGS Germline and Tumor"
* $GTD#M31.7 "Low Grade Glioma, Adult, WGS Germline and Tumor"
* $GTD#M32.6 "Low Grade Glioma/Glioneuronal Tumours, Adult, WGS Germline and Tumor"
* $GTD#M33.5 "Meningioma, Adult, WGS Germline and Tumor"
* $GTD#M34.8 "Non-Midline Glioma, Adult, WGS Germline and Tumor"
* $GTD#M35.9 "OligodendroGlioma, Adult, WGS Germline and Tumor"
* $GTD#M36.16 "Pilocytic Astrocytoma, Adult, WGS Germline and Tumor"
* $GTD#M37.2 "Pineoblastoma, Paediatric, WGS Germline and Tumor"
* $GTD#M38.6 "Pituitary Tumours, WGS Germline and Tumor"
* $GTD#M39.2 "Rare Primitive Neuroectodermal Tumours Groups 2/3, Paediatric, WGS Germline and Tumor"
* $GTD#M80.1 "Acute Myeloid Leukaemia, WGS Germline and Tumor"
* $GTD#M80.57 "Acute Myeloid Leukaemia, WGS Tumour First"
* $GTD#M80.58 "Acute Myeloid Leukaemia, WGS Follow-up Germline"
* $GTD#M82.6 "Myelodysplasia, WGS Germline and Tumor"
* $GTD#M82.23 "Myelodysplasia, WGS Tumour First"
* $GTD#M82.24 "Myelodysplasia, WGS Follow-up Germline"
* $GTD#M83.4 "Aplastic Anaemia, WGS Germline and Tumor"
* $GTD#M83.5 "Aplastic Anaemia, WGS Tumour First"
* $GTD#M83.6 "Aplastic Anaemia, WGS Follow-up Germline"
* $GTD#M84.11 "Chronic Myeloid Leukaemia, WGS Germline and Tumor"
* $GTD#M84.24 "Chronic Myeloid Leukaemia, WGS Tumour First"
* $GTD#M84.25 "Chronic Myeloid Leukaemia, WGS Follow-up Germline"
* $GTD#M85.13 "Myeloproliferative Neoplasm, WGS Germline and Tumor"
* $GTD#M85.37 "Myeloproliferative Neoplasm, WGS Tumour First"
* $GTD#M85.38 "Myeloproliferative Neoplasm, WGS Follow-up Germline"
* $GTD#M86.3 "Systemic Mastocytosis, WGS Germline and Tumor"
* $GTD#M86.4 "Systemic Mastocytosis, WGS Tumour First"
* $GTD#M86.5 "Systemic Mastocytosis, WGS Follow-up Germline"
* $GTD#M88.2 "Juvenile Myelomonocytic Leukaemia, WGS Germline and Tumor"
* $GTD#M88.11 "Juvenile Myelomonocytic Leukaemia, WGS Tumour First"
* $GTD#M88.12 "Juvenile Myelomonocytic Leukaemia, WGS Follow-up Germline"
* $GTD#M89.1 "Acute Leukaemia Other, WGS Germline and Tumor"
* $GTD#M89.108 "Acute Leukaemia Other, WGS Tumour First"
* $GTD#M89.109 "Acute Leukaemia Other, WGS Follow-up Germline"
* $GTD#M90.1 "Blastic Plasmacytoid Dendritic Cell Neoplasm, WGS Germline and Tumor"
* $GTD#M90.6 "Blastic Plasmacytoid Dendritic Cell Neoplasm, WGS Tumour First"
* $GTD#M90.7 "Blastic Plasmacytoid Dendritic Cell Neoplasm, WGS Follow-up Germline"
* $GTD#M91.1 "Acute Lymphoblastic Leukaemia, WGS Germline and Tumor"
* $GTD#M91.82 "Acute Lymphoblastic Leukaemia, WGS Tumour First"
* $GTD#M91.83 "Acute Lymphoblastic Leukaemia, WGS Follow-up Germline"
* $GTD#M93.3 "Lymphoma, WGS Germline and Tumor"
* $GTD#M93.4 "Lymphoma, WGS Tumour First"
* $GTD#M93.5 "Lymphoma, WGS Follow-up Germline"
* $GTD#M95.7 "B Cell Non-Hodgkin Lymphoma, WGS Germline and Tumor"
* $GTD#M95.10 "B Cell Non-Hodgkin Lymphoma, WGS Tumour First"
* $GTD#M95.11 "B Cell Non-Hodgkin Lymphoma, WGS Follow-up Germline"
* $GTD#M96.7 "Burkitt Lymphoma, WGS Germline and Tumor"
* $GTD#M96.9 "Burkitt Lymphoma, WGS Tumour First"
* $GTD#M96.10 "Burkitt Lymphoma, WGS Follow-up Germline"
* $GTD#M97.2 "Burkitt Like Lymphoma with 11q Abnormalities, WGS Germline and Tumor"
* $GTD#M97.4 "Burkitt Like Lymphoma with 11q Abnormalities, WGS Tumour First"
* $GTD#M97.5 "Burkitt Like Lymphoma with 11q Abnormalities, WGS Follow-up Germline"
* $GTD#M98.2 "Large B Cell Like Lymphoma with IRF4 Rearrangement, WGS Germline and Tumor"
* $GTD#M98.4 "Large B Cell Like Lymphoma with IRF4 Rearrangement, WGS Tumour First"
* $GTD#M98.5 "Large B Cell Like Lymphoma with IRF4 Rearrangement, WGS Follow-up Germline"
* $GTD#M99.8 "High Grade Lymphoma, WGS Germline and Tumor"
* $GTD#M99.10 "High Grade Lymphoma, WGS Tumour First"
* $GTD#M99.11 "High Grade Lymphoma, WGS Follow-up Germline"
* $GTD#M100.4 "Primary Mediastinal B Cell Lymphoma, WGS Germline and Tumour"
* $GTD#M100.7 "Primary Mediastinal B Cell Lymphoma, WGS Tumour First"
* $GTD#M100.8 "Primary Mediastinal B Cell Lymphoma, WGS Follow-up Germline"
* $GTD#M101.4 "ALK Positive Large B Cell Lymphoma, WGS Germline and Tumour"
* $GTD#M101.6 "ALK Positive Large B Cell Lymphoma, WGS Tumour First"
* $GTD#M101.7 "ALK Positive Large B Cell Lymphoma, WGS Follow-up Germline"
* $GTD#M107.7 "Malt-Lymphoma, WGS Germline and Tumour"
* $GTD#M107.9 "Malt-Lymphoma, WGS Tumour First"
* $GTD#M107.10 "Malt-Lymphoma, WGS Follow-up Germline"
* $GTD#M110.2 "Paediatric Type Follicular Lymphoma, WGS Germline and Tumour"
* $GTD#M110.3 "Paediatric Type Follicular Lymphoma, WGS Tumour First"
* $GTD#M110.4 "Paediatric Type Follicular Lymphoma, WGS Follow-up Germline"
* $GTD#M111.5 "T Cell Non-Hodgkin Lymphoma, WGS Germline and Tumour"
* $GTD#M111.7 "T Cell Non-Hodgkin Lymphoma, WGS Tumour First"
* $GTD#M111.8 "T Cell Non-Hodgkin Lymphoma, WGS Follow-up Germline"
* $GTD#M112.5 "ALK Negative Anaplastic Large Cell Lymphoma (Including Primary Cutaneous Subtypes), WGS Germline and Tumour"
* $GTD#M112.7 "ALK Negative Anaplastic Large Cell Lymphoma (Including Primary Cutaneous Subtypes), WGS Tumour First"
* $GTD#M112.8 "ALK Negative Anaplastic Large Cell Lymphoma (Including Primary Cutaneous Subtypes), WGS Follow-up Germline"
* $GTD#M115.2 "NK Cell/Gamma-Delta T Cell Lymphoma, WGS Germline and Tumour"
* $GTD#M115.3 "NK Cell/Gamma-Delta T Cell Lymphoma, WGS Tumour First"
* $GTD#M115.4 "NK Cell/Gamma-Delta T Cell Lymphoma, WGS Follow-up Germline"
* $GTD#M116.3 "Hepatosplenic T Cell Lymphoma, WGS Germline and Tumour"
* $GTD#M116.5 "Hepatosplenic T Cell Lymphoma, WGS Tumour First"
* $GTD#M116.6 "Hepatosplenic T Cell Lymphoma, WGS Follow-up Germline"
* $GTD#M117.16 "Histiocytosis, WGS Germline and Tumour"
* $GTD#M117.17 "Histiocytosis, WGS Tumour First"
* $GTD#M117.18 "Histiocytosis, WGS Follow-up Germline"
* $GTD#M120.16 "Atypical Teratoid/Rhabdoid Tumour, Paediatric, WGS Germline and Tumour"
* $GTD#M126.2 "CNS High-Grade Neuroepithelial Tumour with MN1 Alteration, Paediatric, WGS Germline and Tumour"
* $GTD#M130.4 "Cribriform Neuroepithelial Tumour, Paediatric, WGS Germline and Tumour"
* $GTD#M132.12 "Desmoplastic Infantile Gangliogliomas, Paediatric, WGS Germline and Tumour"
* $GTD#M133.3 "Desmoplastic Medulloblastoma, Paediatric, WGS Germline and Tumour"
* $GTD#M136.2 "Fibrolamellar Hepatocellular Carcinoma, Paediatric, WGS Germline and Tumour"
* $GTD#M137.13 "Ganglioglioma, Paediatric, WGS Germline and Tumour"
* $GTD#M138.2 "Glial Tumours, Paediatric, WGS Germline and Tumour"
* $GTD#M139.16 "Glioblastoma, Paediatric, WGS Germline and Tumour"
* $GTD#M145.13 "Medulloblastoma, Paediatric, WGS Germline and Tumour"
* $GTD#M146.6 "Medulloblastoma Group 3, Paediatric, WGS Germline and Tumour"
* $GTD#M147.7 "Medulloblastoma Group 3/4, Paediatric, WGS Germline and Tumour"
* $GTD#M148.8 "Medulloblastoma TP53 WT, Paediatric, WGS Germline and Tumour"
* $GTD#M150.6 "Meningioma, Paediatric, WGS Germline and Tumour"
* $GTD#M153.4 "Nodular Brain Tumour, Paediatric, WGS Germline and Tumor"
* $GTD#M155.3 "Oligoastrocytoma, Paediatric, WGS Germline and Tumor"
* $GTD#M156.8 "Oligodendroglioma, Paediatric, WGS Germline and Tumor"
* $GTD#M158.5 "Pilocytic Astrocytoma, Paediatric, WGS Germline and Tumor"
* $GTD#M159.4 "Pituitary Blastoma, Paediatric, WGS Germline and Tumour"
* $GTD#M160.14 "Pleomorphic Xanthoastrocytoma, Paediatric, WGS Germline and Tumour"
* $GTD#M162.8 "Primitive Neuroectodermal Tumours, Paediatric, WGS Germline and Tumor"
* $GTD#M168.5 "Rosette-Forming Glioneuronal Tumour, Paediatric, WGS Germline and Tumor"
* $GTD#M169.4 "Secondary Glioblastoma, Paediatric, WGS Germline and Tumor"
* $GTD#M170.6 "SHH Medulloblastoma, Paediatric, WGS Germline and Tumor"
* $GTD#M171.7 "SHH Medulloblastoma, TP53 WT, Paediatric, WGS Germline and Tumor"
* $GTD#M172.6 "SHH Medulloblastoma, TP53 MUTANT, Paediatric, WGS Germline and Tumor"
* $GTD#M179.8 "WNT Medulloblastoma, Paediatric, WGS Germline and Tumor"
* $GTD#M182.3 "ALK Positive Anaplastic Large Cell Lymphoma, WGS Germline and Tumor"
* $GTD#M182.5 "ALK Positive Anaplastic Large Cell Lymphoma, WGS Tumour First"
* $GTD#M182.6 "ALK Positive Anaplastic Large Cell Lymphoma, WGS Follow-up Germline"
* $GTD#M183.5 "Diffuse Midline Glioma, Paediatric, WGS Germline and Tumor"
* $GTD#M184.2 "Glioma, Paediatric, WGS Germline and Tumor"
* $GTD#M185.2 "High Grade Glioma, Paediatric, WGS Germline and Tumor"
* $GTD#M186.2 "Low Grade Glioma, Paediatric, WGS Germline and Tumor"
* $GTD#M189.17 "Brain Tumour, No Further Morphological Classification, Paediatric, WGS Germline and Tumor"
* $GTD#M190.30 "Embryonal Tumour Differential, Adult and Paediatric, WGS Germline and Tumor"
* $GTD#M191.22 "Low Grade Intrinsic Brain Tumour Differential, Adult, WGS Germline and Tumor"
* $GTD#M192.23 "High Grade Intrinsic Brain Tumour Differential, Adult, WGS Germline and Tumor"
* $GTD#M193.23 "Unable To Grade Intrinsic Brain Tumour, Adult, WGS Germline and Tumor"
* $GTD#M194.22 "Medulloblastoma all Subtypes, WGS Germline and Tumor"
* $GTD#M195.3 "Craniopharyngioma, Adult and Paediatric, WGS Germline and Tumor"
* $GTD#M213.37 "Glial and Glioneuronal Tumour Differential, Paediatric, WGS Germline and Tumor"
* $GTD#M224.4 "MDS/MPN, WGS Germline and Tumor"
* $GTD#M224.41 "MDS/MPN, WGS Tumour First"
* $GTD#M224.42 "MDS/MPN, WGS Follow-up Germline"
* $GTD#M235.1 "Proven or Suspected Haematological Tumours Exhausted all Standard of Care Testing and Treatment, WGS Germline and Tumor"
* $GTD#M235.2 "Proven or Suspected Haematological Tumours Exhausted all Standard of Care Testing and Treatment, WGS Tumour First"
* $GTD#M235.3 "Proven or Suspected Haematological Tumours Exhausted all Standard of Care Testing and Treatment, WGS Follow-up Germline"
