CodeSystem: GenomicTestOutcomeCode
Id: GenomicTestOutcomeCode
Title: "Genomic Test Outcome Code"
Description: """
Test Outcome Code from [NHS England Genomics Test Reporting Specification](https://www.england.nhs.uk/publication/genomics-testing-reporting-specification/)
"""

* ^name = "GenomicTestOutcomeCode"
* ^content = #fragment
* ^caseSensitive = true
* ^experimental = false
* ^status = #draft
* ^version = "0.0.1"
* ^date = "2025-05-08"
* ^url = "https://nw-gmsa.github.io/CodeSystem/GenomicTestOutcomeCode"

* #11 "WHOLE GENOME SEQUENCING"
* #12 "WHOLE EXOME SEQUENCING"
* #21 "LARGE NEXT GENERATION SEQUENCING PANEL (MORE THAN 100 TARGETS/GENES)"
* #22 "MEDIUM NEXT GENERATION SEQUENCING PANEL (BETWEEN 20-100 TARGETS/GENES)"
* #23 "SMALL NEXT GENERATION SEQUENCING PANEL (LESS THAN 20 TARGETS/GENES)"
* #31 "CHROMOSOMAL MICROARRAY"
* #32 "PYROSEQUENCING"
* #34 "SANGER SEQUENCING LESS THAN 10 AMPLICONS"

* #35 "SANGER SEQUENCING GREATER THAN OR EQUAL TO 10 AMPLICONS"
* #36 "KARYOTYPE"
* #37 "FLUORESCENCE IN SITU HYBRIDISATION (FISH)"
* #38 "MULTIPLEX LIGATION-DEPENDENT PROBE AMPLIFICATION"
* #39 "METHYLATION SPECIFIC POLYMERASE CHAIN REACTION"

* #40 "TARGETED VARIANT TESTING"
* #41 "QUANTITATIVE POLYMERASE CHAIN REACTION (PCR)"
* #42 "QUALITATIVE POLYMERASE CHAIN REACTION (PCR)"
* #43 "QUANTITATIVE REVERSE TRANSCRIPTION POLYMERASE CHAIN REACTION (RT-PCR)"
* #44 "QUALITATIVE REVERSE TRANSCRIPTION POLYMERASE CHAIN REACTION (RT-PCR)"
* #45 "SHORT TANDEM REPEAT (STR) TESTING"
* #46 "LINKAGE ANALYSIS"
* #47 "UNIPARENTAL DISOMY (UPD) TESTING"
* #48 "MICROSATELLITE INSTABILITY (MSI) TESTING"
* #49 "CHROMOSOME BREAKAGE"
* #50 "MITOCHONDRIAL GENOME SEQUENCING"
* #51 "SOUTHERN BLOT ANALYSIS"
* #52 "METHYLATION MICROARRAY"
* #53 "DIGITAL DROPLET PCR (ddPCR)"
* #54 "LOOP-MEDIATED AMPLIFICATION (LAMP)"
* #55 "RELATIVE HAPLOTYPE DOSAGE (RHDO)"
* #56 "MASSIVELY PARALLEL SHOTGUN SEQUENCING"
* #57 "MICROARRAY FOR NIPT"
* #58 "RAPID WHOLE GENOME SEQUENCING"
* #59 "MASS SPECTROMETRY (including MALDITOF and MASS-Array)"
* #98 "OTHER (NOT LISTED)"

