@startuml

title "Search and Retrieve a Document"

agent "Document Consumer" as Consumer

node "Document Responder" {
agent "Document Registry" as Registry
agent "Document Repository" as Repository
Registry -d[hidden]- Repository
}

Consumer -r-> Registry: [[https://profiles.ihe.net/ITI/TF/Volume2/ITI-18.html Registry Stored Query (ITI-18)]]\n[[https://profiles.ihe.net/ITI/MHD/ITI-67.html Find Document References (ITI-67)]]
Consumer -r-> Repository: [[https://profiles.ihe.net/ITI/TF/Volume2/ITI-43.html Retrieve Document Set (ITI-43)]]\n[[https://profiles.ihe.net/ITI/MHD/ITI-68.html Retrieve Document (ITI-68)]]

@enduml
