@startuml

hide footbox

title "Traditional Messaging"

participant "Order Placer" as EPR
participant "Order Filler" as LIMS


EPR -> EPR: Complete Order Form
EPR -> LIMS: [[LAB-1.html Placer Order Managment (LAB-1)]] [[Questionnaire-GenomicTestOrder.html Genomic Order O21]] Command Message
alt accepted
LIMS -> LIMS: Perform Test
opt preliminary/partial reports
LIMS -> LIMS: Create preliminary/partial report
LIMS -> EPR: [[LAB-3.html Order Results Management (LAB-3)]] [[StructureDefinition-Composition-GenomicReport.html Genomic Report R01]] Document Message
end
LIMS -> LIMS: Create final report
LIMS -> EPR: [[LAB-3.html Order Results Management (LAB-3)]] [[StructureDefinition-Composition-GenomicReport.html Genomic Report R01]] Document Message
else rejected
LIMS -> EPR: General laboratory order response message O22
end

@enduml
