@startuml

hide footbox


participant "Order Filler" as LIMS
participant "Automation Manager" as Device

LIMS -> Device: \nSend** Work Order Manangment LAB-4 O21**
Device -> Device: Perform Tests
Device -> LIMS: \nSend** Test Results Management LAB-5 R22/R32**

@enduml