CodeSystem: GenomicClinicalIndication
Id: GenomicClinicalIndication
Title: "NHS England Genomic Clinical Indication Code"
Description: """
1st level Genomic Test Directory Codes - completed from the same master
spreadsheets as `GenomicTestCode` (`EnglandTestCode.fsh`); see that CodeSystem's
own Description for the legacy-versus-current distinction, which applies the
same way here.
"""

* ^name = "GenomicClinicalIndication"
* ^content = #fragment
* ^caseSensitive = true
* ^experimental = false
* ^status = #active
* ^version = "2026.09.05"
* ^date = "2026-09-05"
* ^url = "https://fhir.nwgenomics.nhs.uk/CodeSystem/GenomicClinicalIndication"

// R* - Rare & Inherited Disease (v9)

* #R14 "Acutely unwell children with a likely monogenic disorder"
* #R15 "Primary immunodeficiency or monogenic inflammatory bowel disease"
* #R16 "Severe combined immunodeficiency with adenosine deaminase deficiency"
* #R17 "Lymphoproliferative syndrome with absent SAP expression"
* #R18 "Haemophagocytic syndrome with absent XIAP expression"
* #R19 "Autoimmune lymphoproliferative syndrome with defective apoptosis"
* #R20 "Wiskott-Aldrich syndrome"
* #R21 "Fetal anomalies with a likely genetic cause"
* #R22 "Fetus with a likely chromosomal abnormality"
* #R23 "Apert syndrome"
* #R24 "Achondroplasia"
* #R25 "Thanatophoric dysplasia"
* #R26 "Likely common aneuploidy"
* #R27 "Paediatric disorders"
* #R28 "Congenital malformation and dysmorphism syndromes"
* #R31 "Bilateral congenital or childhood onset cataracts"
* #R32 "Retinal disorders"
* #R33 "Possible X-linked retinitis pigmentosa"
* #R36 "Structural eye disease"
* #R38 "Sporadic aniridia"
* #R39 "Albinism or congenital nystagmus"
* #R41 "Optic neuropathy"
* #R42 "Leber hereditary optic neuropathy"
* #R43 "Blepharophimosis ptosis and epicanthus inversus"
* #R45 "Stickler syndrome"
* #R46 "Congenital fibrosis of the extraocular muscles"
* #R47 "Angelman syndrome"
* #R48 "Prader-Willi syndrome"
* #R49 "Beckwith-Wiedemann syndrome"
* #R50 "Isolated hemihypertrophy or macroglossia"
* #R52 "Short stature - SHOX deficiency"
* #R54 "Hereditary ataxia with onset in adulthood"
* #R55 "Hereditary ataxia with onset in childhood"
* #R56 "Adult onset dystonia, chorea or related movement disorder"
* #R57 "Childhood onset dystonia, chorea or related movement disorder"
* #R60 "Adult onset hereditary spastic paraplegia"
* #R61 "Childhood onset hereditary spastic paraplegia"
* #R62 "Adult onset leukodystrophy"
* #R63 "Possible mitochondrial disorder - nuclear genes"
* #R64 "MELAS or MIDD"
* #R65 "Aminoglycoside exposure posing risk to hearing"
* #R66 "Paroxysmal central nervous system disorders"
* #R67 "Monogenic hearing loss"
* #R68 "Huntington disease"
* #R69 "Hypotonic infant"
* #R70 "Spinal muscular atrophy type 1 diagnostic test"
* #R71 "Spinal muscular atrophy type 1 rare variant testing"
* #R72 "Myotonic dystrophy type 1"
* #R73 "Duchenne or Becker muscular dystrophy"
* #R74 "Facioscapulohumeral muscular dystrophy"
* #R75 "Oculopharyngeal muscular dystrophy"
* #R76 "Skeletal muscle channelopathy"
* #R77 "Hereditary neuropathy - PMP22 copy number"
* #R78 "Hereditary neuropathy or pain disorder"
* #R79 "Congenital muscular dystrophy"
* #R80 "Congenital myaesthenic syndrome"
* #R81 "Congenital myopathy"
* #R82 "Limb girdle muscular dystrophies, myofibrillar myopathies and distal myopathies"
* #R83 "Arthrogryposis"
* #R84 "Cerebellar anomalies"
* #R85 "Holoprosencephaly - NOT chromosomal"
* #R86 "Hydrocephalus"
* #R87 "Cerebral malformation"
* #R88 "Severe microcephaly"
* #R89 "Ultra-rare and atypical monogenic disorders"
* #R90 "Bleeding and platelet disorders"
* #R91 "Cytopenia - NOT Fanconi anaemia"
* #R92 "Rare anaemia"
* #R93 "Sickle cell, thalassaemia and other haemoglobinopathies"
* #R95 "Iron overload - hereditary haemochromatosis testing"
* #R96 "Iron metabolism disorders - NOT common HFE  variants"
* #R97 "Thrombophilia with a likely monogenic cause"
* #R98 "Likely inborn error of metabolism"
* #R99 "Common craniosynostosis syndromes"
* #R100 "Rare syndromic craniosynostosis or isolated multisuture synostosis"
* #R101 "Ehlers Danlos syndrome with a likely monogenic cause"
* #R102 "Osteogenesis imperfecta"
* #R104 "Skeletal dysplasia"
* #R105 "MCADD - Medium-chain acyl-CoA dehydrogenase deficiency – common variant newborn screening follow up"
* #R106 "Alstrom syndrome"
* #R107 "Bardet Biedl syndrome"
* #R109 "Childhood onset leukodystrophy"
* #R110 "Segmental overgrowth disorders - Deep sequencing"
* #R111 "X-inactivation testing"
* #R112 "Factor II deficiency"
* #R115 "Factor V deficiency"
* #R116 "Factor VII deficiency"
* #R117 "Factor VIII deficiency"
* #R118 "Factor IX deficiency"
* #R119 "Factor X deficiency"
* #R120 "Factor XI deficiency"
* #R121 "von Willebrand disease"
* #R122 "Factor XIII deficiency"
* #R123 "Combined vitamin K-dependent clotting factor deficiency"
* #R124 "Combined factor V and VIII deficiency"
* #R125 "Thoracic aortic aneurysm or dissection"
* #R127 "Long QT syndrome"
* #R128 "Brugada syndrome and cardiac sodium channel disease"
* #R129 "Catecholaminergic polymorphic VT"
* #R130 "Short QT syndrome"
* #R131 "Hypertrophic cardiomyopathy"
* #R132 "Dilated and Arrhythmogenic cardiomyopathy"
* #R133 "Arrhythmogenic right ventricular cardiomyopathy"
* #R134 "Familial hypercholesterolaemia"
* #R135 "Paediatric or syndromic cardiomyopathy"
* #R136 "Primary lymphoedema"
* #R137 "Congenital heart disease - microarray"
* #R138 "Sudden unexplained death or survivors of a cardiac event"
* #R139 "Laterality disorders and isomerism"
* #R140 "Elastin-related phenotypes"
* #R141 "Monogenic diabetes"
* #R142 "Glucokinase-related fasting hyperglycaemia"
* #R143 "Neonatal diabetes"
* #R144 "Congenital hyperinsulinism"
* #R145 "Congenital hypothyroidism"
* #R146 "Differences in sex development"
* #R148 "Hypogonadotropic hypogonadism"
* #R149 "Severe early-onset obesity"
* #R150 "Congenital adrenal hypoplasia"
* #R151 "Familial hyperparathyroidism or Hypocalciuric hypercalcaemia"
* #R153 "Familial hypoparathyroidism"
* #R154 "Hypophosphataemia or rickets"
* #R155 "Autoimmune Polyendocrine Syndrome"
* #R156 "Carney complex"
* #R157 "IPEX - Immunodysregulation Polyendocrinopathy and Enteropathy, X-Linked"
* #R158 "Severe insulin resistance and lipodystrophy syndromes"
* #R159 "Pituitary hormone deficiency"
* #R160 "Primary pigmented nodular adrenocortical disease"
* #R162 "Familial tumoral calcinosis"
* #R163 "Ectodermal dysplasia"
* #R164 "Epidermolysis bullosa and congenital skin fragility"
* #R165 "Ichthyosis and erythrokeratoderma"
* #R166 "Palmoplantar keratodermas"
* #R167 "Autosomal recessive primary hypertrophic osteoarthropathy"
* #R168 "Non-acute porphyrias"
* #R169 "Acute intermittent porphyria"
* #R170 "Variegate porphyria"
* #R171 "Cholestasis"
* #R172 "Wilson disease"
* #R173 "Polycystic liver disease"
* #R175 "Pancreatitis"
* #R176 "Gilbert syndrome"
* #R180 "Congenital adrenal hyperplasia diagnostic test"
* #R181 "Congenital adrenal hyperplasia carrier testing"
* #R182 "Hyperthyroidism"
* #R183 "Glucocorticoid-remediable aldosteronism (GRA)"
* #R184 "Cystic fibrosis diagnostic test"
* #R185 "Cystic fibrosis carrier testing"
* #R186 "Hereditary haemorrhagic telangiectasia"
* #R188 "Pulmonary arterial hypertension"
* #R189 "Respiratory ciliopathies including non-CF bronchiectasis"
* #R190 "Pneumothorax - familial"
* #R191 "Alpha-1-antitrypsin deficiency"
* #R193 "Cystic renal disease"
* #R194 "Haematuria"
* #R195 "Proteinuric renal disease"
* #R196 "CFHR5 nephropathy"
* #R197 "Membranoproliferative glomerulonephritis including C3 glomerulopathy"
* #R198 "Renal tubulopathies"
* #R199 "Congenital anomalies of the kidney and urinary tract - familial"
* #R201 "Atypical haemolytic uraemic syndrome"
* #R202 "Tubulointerstitial kidney disease"
* #R204 "Hereditary Systemic Amyloidosis"
* #R207 "Inherited ovarian cancer (without breast cancer)"
* #R208 "Inherited breast cancer and ovarian cancer"
* #R210 "Inherited MMR deficiency (Lynch syndrome)"
* #R211 "Inherited polyposis and early onset colorectal cancer - germline testing"
* #R212 "Peutz Jeghers Syndrome"
* #R213 "PTEN Hamartoma Tumor Syndrome"
* #R214 "Nevoid Basal Cell Carcinoma Syndrome or Gorlin syndrome"
* #R215 "Hereditary diffuse gastric cancer"
* #R216 "Li Fraumeni Syndrome"
* #R217 "Endocrine neoplasia"
* #R218 "Multiple endocrine neoplasia type 2"
* #R219 "Retinoblastoma"
* #R221 "Familial tumours of the nervous system"
* #R222 "Neurofibromatosis type 1"
* #R223 "Inherited phaeochromocytoma and paraganglioma excluding NF1"
* #R224 "Inherited renal cancer"
* #R225 "Von Hippel Lindau syndrome"
* #R226 "Inherited parathyroid cancer"
* #R227 "Xeroderma pigmentosum, Trichothiodystrophy or Cockayne syndrome"
* #R228 "Tuberous sclerosis"
* #R229 "Confirmed Fanconi anaemia or Bloom syndrome - variant testing"
* #R230 "Multiple monogenic benign skin tumours"
* #R231 "Neuronal ceroid lipofuscinosis"
* #R232 "Haemophagocytic syndrome with absent perforin expression"
* #R233 "Agammaglobulinaemia with absent BTK expression"
* #R234 "Severe combined immunodeficiency with PNP deficiency"
* #R235 "SCID with features of gamma chain deficiency"
* #R236 "Pigmentary skin disorders"
* #R237 "Cutaneous photosensitivity with a likely genetic cause"
* #R239 "Incontinentia pigmenti"
* #R240 "Diagnostic testing for known variant(s)"
* #R242 "Predictive testing for known familial variant(s)"
* #R244 "Carrier testing for known familial variant(s)"
* #R246 "Carrier testing at population risk for partners of known carriers of nationally agreed autosomal recessive disorders"
* #R249 "NIPD using paternal exclusion testing for very rare conditions where familial variant is known"
* #R250 "NIPD for congenital adrenal hyperplasia - CYP21A2 haplotype testing"
* #R251 "Non-invasive prenatal sexing"
* #R252 "SMA carrier testing at population risk for partners of known carriers"
* #R253 "Cystic fibrosis newborn screening follow-up"
* #R254 "Familial melanoma"
* #R255 "Epidermodysplasia verruciformis"
* #R256 "Nephrocalcinosis or nephrolithiasis"
* #R257 "Unexplained young onset end-stage renal disease"
* #R258 "Cytopenia - Fanconi breakage testing indicated"
* #R259 "Nijmegen breakage syndrome"
* #R260 "Fanconi anaemia or Bloom syndrome - chromosome breakage testing"
* #R262 "Corneal dystrophy"
* #R263 "Confirmation of uniparental disomy"
* #R264 "Identity testing"
* #R265 "Chromosomal mosaicism - karyotype"
* #R268 "Kagami-Ogata syndrome - paternal uniparental disomy 14"
* #R270 "Smith-Lemli-Opitz syndrome"
* #R271 "Neuronal ceroid lipofuscinosis type 2"
* #R272 "Gaucher disease"
* #R273 "Glycogen storage disease V"
* #R274 "Glycogen storage disease"
* #R275 "Glutaric acidaemia I newborn screening follow up"
* #R276 "Lysosomal storage disorder"
* #R277 "Mucopolysaccharidosis type IH/S"
* #R278 "Mucopolysaccharidosis type II"
* #R279 "Isovaleric acidaemia newborn screening follow up"
* #R280 "Krabbe disease – GALC deficiency"
* #R281 "Krabbe disease - Saposin A deficiency"
* #R282 "Niemann-Pick disease type A or B"
* #R283 "Phenylketonuria"
* #R285 "Sandhoff disease"
* #R286 "Tay-Sachs disease"
* #R287 "Mucopolysaccharidosis type IVA"
* #R288 "GM1 Gangliosidosis and Mucopolysaccharidosis Type IVB"
* #R289 "Mucolipidosis II and III Alpha/Beta"
* #R290 "Mucopolysaccharidosis type VI"
* #R291 "Mucopolysaccharidosis type IIIA"
* #R292 "Mucopolysaccharidosis type IIIB"
* #R293 "Albright hereditary osteodystrophy, pseudohypoparathyroidism, pseudopseudohypoparathyroidism, acrodysostosis and osteoma cutis"
* #R294 "Ataxia telangiectasia - DNA repair testing"
* #R295 "Ataxia telangiectasia - variant testing"
* #R296 "RNA analysis of variants"
* #R298 "Possible structural or mosaic chromosomal abnormality - FISH"
* #R299 "Possible mitochondrial disorder - mitochondrial DNA rearrangement testing"
* #R300 "Possible mitochondrial disorder - whole mitochondrial genome sequencing"
* #R301 "Possible mitochondrial disorder - mitochondrial DNA depletion testing"
* #R304 "NIPD for cystic fibrosis - haplotype testing"
* #R305 "NIPD for cystic fibrosis - variant testing"
* #R306 "NIPD for Apert syndrome - variant testing"
* #R307 "NIPD for Crouzon syndrome with acanthosis nigricans - variant testing"
* #R308 "NIPD for FGFR2-related craniosynostosis syndromes - variant testing"
* #R309 "NIPD for FGFR3-related skeletal dysplasias - variant testing"
* #R310 "NIPD for Duchenne and Becker muscular dystrophy - haplotype testing"
* #R311 "NIPD for spinal muscular atrophy - variant testing"
* #R312 "Parental sequencing for lethal autosomal recessive disorders"
* #R313 "Neutropaenia consistent with ELANE variants"
* #R314 "Ambiguous genitalia"
* #R315 "POLG-related disorder"
* #R316 "Pyruvate dehydrogenase (PDH) deficiency"
* #R317 "Mitochondrial liver disease, including transient infantile liver failure"
* #R318 "Recurrent miscarriage with products of conception available for testing"
* #R319 "Calcium-sensing receptor phenotypes"
* #R320 "Invasive prenatal diagnosis requiring fetal sexing"
* #R321 "Maternal cell contamination testing"
* #R322 "Skin fibroblasts to be cultured and stored"
* #R323 "Sitosterolaemia"
* #R324 "Familial Chylomicronaemia Syndrome (FCS)"
* #R325 "Lysosomal acid lipase deficiency"
* #R326 "Vascular skin disorders"
* #R327 "Mosaic skin disorders - deep sequencing"
* #R328 "Progressive cardiac conduction disease"
* #R329 "Familial dysalbuminaemic hyperthyroxinaemia"
* #R330 "Alveolar capillary dysplasia with misalignment of pulmonary veins"
* #R331 "Intestinal failure or congenital diarrhoea"
* #R332 "Rare genetic inflammatory skin disorders"
* #R333 "Central congenital hypoventilation"
* #R334 "Cystinosis"
* #R335 "Fabry disease"
* #R336 "Cerebral vascular malformations"
* #R337 "CADASIL"
* #R338 "Monitoring for G(M)CSF escape variants"
* #R340 "Amelogenesis imperfecta"
* #R341 "Hereditary angioedema types I and II"
* #R343 "Chromosomal mosaicism - microarray"
* #R344 "Primary hyperaldosteronism - KCNJ5"
* #R345 "Facioscapulohumeral muscular dystrophy - extended testing"
* #R346 "DNA to be stored"
* #R347 "Inherited predisposition to acute myeloid leukaemia (AML)"
* #R350 "MERRF syndrome"
* #R351 "NARP syndrome or maternally inherited Leigh syndrome"
* #R352 "Mitochondrial DNA maintenance disorder"
* #R353 "Mitochondrial disorder with complex I deficiency"
* #R354 "Mitochondrial disorder with complex II deficiency"
* #R355 "Mitochondrial disorder with complex III deficiency"
* #R356 "Mitochondrial disorder with complex IV deficiency"
* #R357 "Mitochondrial disorder with complex V deficiency"
* #R361 "Sickle cell, thalassaemia and other haemoglobinopathies trait or carrier testing"
* #R363 "Inherited predisposition to GIST"
* #R364 "DICER1-related cancer predisposition"
* #R365 "Fumarate hydratase-related tumour syndromes"
* #R366 "Inherited susceptibility to acute lymphoblastoid leukaemia (ALL)"
* #R367 "Inherited pancreatic cancer"
* #R368 "Hereditary angioedema type III"
* #R370 "Validation of unaccredited findings"
* #R371 "Malignant hyperthermia"
* #R372 "Newborn screening for sickle cell disease in a transfused baby"
* #R373 "RNA to be stored"
* #R374 "Other sample to be stored"
* #R375 "Family follow-up testing to aid variant interpretation"
* #R376 "Segmental or atypical neurofibromatosis type 1 testing"
* #R380 "Niemann Pick disease type C"
* #R381 "Other rare neuromuscular disorders"
* #R382 "Hypochondroplasia"
* #R383 "Linkage testing for Huntington disease"
* #R384 "Generalised arterial calcification in infancy"
* #R387 "Reanalysis of existing data"
* #R389 "NIPD - pre-pregnancy test work-up"
* #R390 "Multiple exostoses"
* #R391 "Barth syndrome"
* #R394 "Mitochondrial neurogastrointestinal encephalopathy"
* #R395 "Thiamine metabolism dysfunction syndrome 2"
* #R396 "Mitochondrial Complex V deficiency, TMEM70 type"
* #R397 "Maternally inherited cardiomyopathy"
* #R401 "Common aneuploidy testing - prenatal"
* #R402 "Premature ovarian insufficiency"
* #R403 "MCADD - Medium-chain acyl-CoA dehydrogenase deficiency – full ACADM sequencing newborn screening follow up"
* #R404 "Testing of unaffected individuals for inherited cancer predisposition syndromes"
* #R405 "Hereditary Erythrocytosis"
* #R406 "Thrombocythaemia"
* #R409 "Linkage testing for other recognisable Mendelian disorders"
* #R410 "Myotonic dystrophy type 2 (DM2)"
* #R411 "Y chromosome microdeletion"
* #R412 "Fetal anomalies with a likely genetic cause - non urgent"
* #R413 "Autoinflammatory Disorders"
* #R414 "APC associated Polyposis"
* #R416 "Syndromic and non syndromic craniosynostosis involving midline sutures"
* #R417 "Multi Locus Imprinting Disorder (MLID)"
* #R419 "Acute Rhabdomyolysis"
* #R420 "Pseudoxanthoma elasticum"
* #R421 "Pulmonary Fibrosis, Familial"
* #R422 "BAP1 associated tumour predisposition syndrome"
* #R423 "NIPD for Retinoblastoma - haplotype testing"
* #R424 "Subcutaneous panniculitis T-cell lymphoma (SPTCL)"
* #R426 "Pulmonary alveolar microlithiasis"
* #R428 "Patient receiving solid organ transplantation (only in cases where passenger lymphocyte syndrome is suspected)"
* #R430 "Inherited prostate cancer"
* #R431 "Genome-wide DNA Methylation Profiling to Aid Variant Interpretation"
* #R433 "Monogenic diabetes, subtype glucokinase - NIPT"
* #R436 "Hereditary alpha tryptasaemia"
* #R438 "Paediatric pseudo-obstruction syndrome"
* #R440 "Hereditary isolated diabetes insipidus"
* #R441 "Unexplained death in infancy and sudden unexplained death in childhood"
* #R442 "Variant re-interpretation"
* #R443 "Confirmation test"
* #R444 "NICE approved PARP inhibitor treatment"
* #R445 "T21, T18 and T13 aneuploidy testing - NIPT (previous history)"
* #R446 "APOL1 kidney donor testing"
* #R447 "Validation of WGS Diagnostic discovery"
* #R448 "Prenatal testing"
* #R449 "Diagnostic testing for Glutaric acidaemia I"
* #R450 "Diagnostic testing for Isovaleric acidaemia"
* #R451 "Diagnostic testing for MCADD - Medium-chain acyl-CoA dehydrogenase deficiency – full ACADM sequencing"
* #R452 "Silver russell syndrome and Temple Syndrome"
* #R453 "Monogenic short stature"
* #R454 "Mavacamten for treating symptomatic obstructive hypertrophic cardiomyopathy"
* #R456 "Embryonal tumour of possible germline origin"
* #R457 "Sarcoma of possible germline origin"
* #R458 "Young onset or familial dementia"
* #R459 "Young onset or complex Parkinson disease"
* #R460 "Amyotrophic lateral sclerosis"
* #R461 "Cerebral amyloid angiopathy"
* #R462 "Childhood interstitial lung disease"
* #R463 "Cytogenetic characterisation of a genomic abnormality – Karyotype or Targeted Chromosome Analysis"
* #R464 "Recurrent miscarriage where products of conception are not available for testing - parental karyotype"
* #R465 "Familial cytogenetic rearrangement - Karyotype or Targeted Chromosome Analysis"
* #R466 "Unexplained infertility - karyotype"
* #R467 "Gamete donors - karyotype"
* #R468 "Possible sex chromosome aneuploidy or structural rearrangement – Targeted Chromosome Analysis"
* #R470 "T21, T18, and T13 aneuploidy testing - NIPT NHS Fetal Anomaly Screening Programme (FASP)"
* #R471 "Neurodegenerative Disorders, adult onset – Prenatal Exclusion Testing"

// M* - Cancer, non-CNS (v16) - still current

* #M1 "Colorectal Carcinoma"
* #M2 "Ovarian Carcinoma"
* #M3 "Breast Cancer"
* #M4 "Non-Small Cell Lung Cancer"
* #M5 "Mesothelioma"
* #M6 "Mucoepidermoid Carcinoma"
* #M7 "Melanoma - Adult"
* #M8 "Gastrointestinal Stromal Tumour"
* #M9 "Thyroid Papillary Carcinoma - Adult"
* #M10 "Thyroid Follicular Carcinoma"
* #M11 "Poorly Differentiated Anaplastic Thyroid Carcinoma"
* #M12 "Thyroid Medullary Carcinoma"
* #M13 "Phaeochromocytoma"
* #M14 "Adrenal Cortical Carcinoma"
* #M15 "Head and Neck Squamous Cell Carcinoma"
* #M16 "Adenoid Cystic Carcinoma"
* #M17 "Secretory Carcinoma (Salivary Gland)"
* #M18 "Renal Cell Carcinoma - Adult"
* #M42 "Alveolar Rhabdomyosarcoma"
* #M43 "Alveolar Soft Part Sarcoma"
* #M44 "Aneurysmal Bone Cyst"
* #M45 "Angiomatoid Fibrous Histiocytoma"
* #M46 "Chondrosarcoma Conventional Central"
* #M47 "Chondroblastoma"
* #M48 "Clear Cell Sarcoma of Soft Tissue"
* #M49 "CNS Ewing Sarcoma Family Tumour With CIC Alteration"
* #M50 "Dermatofibrosarcoma Protuberans"
* #M51 "Desmoid-Type Fibromatosis"
* #M52 "Desmoplastic Small Round Cell Tumour"
* #M53 "Endometrial Stromal Sarcoma"
* #M54 "Epithelioid Haemangioendothelioma"
* #M55 "Ewing Like Sarcoma/PNET"
* #M56 "Ewing Sarcoma of Bone"
* #M57 "Ewing-Like Soft-Tissue Sarcoma"
* #M58 "Extraskeletal Myxoid Chondrosarcoma"
* #M59 "Fibrous Dysplasia/Myxomas (Mazabraud Syndrome)"
* #M60 "Giant Cell Tumour of Bone"
* #M61 "High-Grade Neuroepithelial Tumour-Bcor Group"
* #M62 "Infantile Fibrosarcoma"
* #M63 "Inflammatory Myofibroblastic Tumour"
* #M64 "Low Grade Fibromyxoid Sarcoma"
* #M65 "Mesenchymal Chondrosarcoma"
* #M66 "Myoepithelial Tumours of Soft Tissue"
* #M67 "Myxoid/Round Cell Liposarcoma"
* #M68 "Myxoinflammatory Fibroblastic Sarcoma"
* #M69 "Nodular Fasciitis"
* #M70 "Osteosarcoma"
* #M71 "Phosphaturic Mesenchymal Tumour"
* #M72 "Primitive Mesenchymal Myxoid Tumour of Infancy"
* #M73 "Pseudomyogenic Haemangioendothelioma"
* #M74 "Radiation Induced Angiosarcoma"
* #M75 "Round Cell Sarcoma Nos"
* #M76 "Sclerosing Epithelioid Fibrosarcoma"
* #M77 "Synovial Sarcoma"
* #M78 "Undifferentiated Round Cell Sarcoma of Infancy"
* #M79 "Well Differentiated/Dedifferentiated Liposarcoma"
* #M119 "Paediatric Tumours"
* #M124 "Clear Cell Kidney Sarcoma - Paediatric"
* #M127 "Congenital Mesoblastic Nephroma - Paediatric"
* #M131 "Cystic Nephroma - Paediatric"
* #M143 "Lung - Paediatric"
* #M149 "Melanotic Tumours - Paediatric"
* #M151 "Midline Carcinoma - Paediatric"
* #M152 "Neuroblastoma - Paediatric"
* #M157 "Thyroid Papillary Carcinoma - Paediatric"
* #M161 "Pleuropulmonary Blastoma - Paediatric"
* #M165 "Renal Tumours - Paediatric"
* #M166 "Retinoblastoma - Paediatric"
* #M167 "Rhabdoid Tumours - Paediatric"
* #M173 "t(6;11) Translocation-Associated Renal Cell Carcinoma - Paediatric"
* #M174 "Testicular - Paediatric"
* #M178 "Wilms Tumours - Paediatric"
* #M180 "Xp11.2 Translocation-Associated Renal Cell Carcinoma - Paediatric"
* #M187 "Uveal melanoma"
* #M196 "Bone Forming Soft Tissue Tumour Differential"
* #M197 "Round Cell Sarcoma of Soft Tissue Differential"
* #M198 "Vascular Soft Tissue Tumour Differential"
* #M199 "Spindle Cell Soft Tissue Tumour Differential"
* #M200 "Myxoid Soft Tissue Tumour Differential"
* #M201 "Adipocytic Soft Tissue Tumour Differential"
* #M202 "Epithelioid Soft Tissue Tumour Differential"
* #M203 "Uterine Sarcomas (Inc Endometrial)"
* #M204 "Undifferentiated tumour"
* #M205 "Cartilage Forming Bone Tumour Differential"
* #M206 "Bone Forming Bone Tumour Differential"
* #M207 "Osteoclast-Rich Bone Tumour Differential"
* #M208 "Round Cell Sarcoma of Bone Differential"
* #M209 "Vascular Tumour of Bone Differential"
* #M210 "Spindle Cell Tumour of Bone Differential"
* #M211 "Fibro-Osseous Tumour of Bone Differential"
* #M212 "Renal Tumour Differential - Paediatric"
* #M215 "Endometrial Cancer"
* #M217 "Urothelial Carcinoma"
* #M218 "Prostate Cancer"
* #M219 "Pancreatic Cancer"
* #M220 "Cholangiocarcinoma"
* #M221 "Spitzoid tumour"
* #M222 "Hepatocellular carcinoma"
* #M226 "Carcinoma of Unknown Primary"
* #M227 "Solid tumour other (i.e. specific histology not listed elsewhere in the test directory)"
* #M231 "Small cell lung cancer"
* #M232 "Solid Tumour Exhausted all Standards of Care Testing and Treatment- Adult"
* #M233 "High Grade Ovarian Carcinoma"
* #M234 "Triple Negative Breast Cancer"
* #M236 "Oesophageal Cancer"
* #M237 "Gastric Cancer"
* #M238 "Small Bowel Cancer"
* #M239 "Thyroid Hurtle Cell Carcinoma"
* #M240 "Non-invasive follicular thyroid neoplasm with papillary like nuclei"
* #M241 "Conjunctival melanoma"
* #M242 "Any patient receiving solid organ transplantation (only in cases where passenger lymphocyte syndrome is suspected)"
* #M243 "Thymic Carcinoma"
* #M244 "In all tumours eligible for NTRK1/2/3 testing"
* #M245 "Ovarian sex cord stromal tumours"

// M* - Haematological Oncology / Cancer CNS - superseded by DGTS TP codes, preserved as-is

* #M20 "Anaplastic Astrocytoma"
* #M21 "Astrocytoma"
* #M22 "Diffuse Astrocytoma"
* #M23 "Diffuse Midline Glioma"
* #M24 "Embryonal Tumours with Multi-Layered Rosettes"
* #M25 "Ependymoma"
* #M26 "Ependymoma"
* #M27 "Glioblastoma"
* #M28 "Glioma"
* #M29 "High Grade Glioma"
* #M30 "IDH-Wildtype Glioblastoma"
* #M31 "Low Grade Glioma"
* #M32 "Low Grade Glioma/Glioneuronal Tumours"
* #M33 "Meningioma"
* #M34 "Non-Midline Glioma"
* #M35 "OligodendroGlioma"
* #M36 "Pilocytic Astrocytoma"
* #M37 "Pineoblastoma"
* #M38 "Pituitary Tumours"
* #M39 "Rare Primitive Neuroectodermal Tumours Groups 2/3"
* #M80 "Acute Myeloid Leukaemia"
* #M81 "Transient Abnormal Myelopoiesis"
* #M82 "Myelodysplasia"
* #M83 "Aplastic Anaemia"
* #M84 "Chronic Myeloid Leukaemia"
* #M85 "Myeloproliferative Neoplasm"
* #M86 "Systemic Mastocytosis"
* #M87 "Chronic Neutrophilic Leukaemia"
* #M88 "Juvenile Myelomonocytic Leukaemia"
* #M89 "Acute Leukaemia Other"
* #M90 "Blastic Plasmacytoid Dendritic Cell Neoplasm"
* #M91 "Acute Lymphoblastic Leukaemia"
* #M92 "Plasma Cell Dyscrasia"
* #M93 "Lymphoma"
* #M94 "Chronic Lymphocytic Leukaemia"
* #M95 "B cell Non-Hodgkin Lymphoma"
* #M96 "Burkitt Lymphoma"
* #M97 "Burkitt Like Lymphoma with 11q Abnormalities"
* #M98 "Large B Cell Like Lymphoma with IRF4 Rearrangement"
* #M99 "High Grade Lymphoma"
* #M100 "Primary Mediastinal B Cell Lymphoma"
* #M101 "ALK Positive Large B Cell Lymphoma"
* #M102 "Mantle Cell Lymphoma"
* #M103 "Follicular Lymphoma"
* #M104 "Lymphoplasmacytic Lymphoma/Waldenstrom Macroglobulinaemia"
* #M105 "Igm Monoclonal Gammopathy of Uncertain Significance"
* #M106 "Intra-Ocular Lymphoma"
* #M107 "Malt-Lymphoma"
* #M108 "Hairy Cell Leukaemia"
* #M109 "Hairy Cell Leukaemia"
* #M110 "Paediatric Type Follicular Lymphoma"
* #M111 "T Cell Non-Hodgkin Lymphoma"
* #M112 "ALK Negative Anaplastic Large Cell Lymphoma (Including Primary Cutaneous Subtypes)"
* #M113 "T Prolymphocytic Leukaemia"
* #M114 "Large Granular Lymphocyte Leukaemia"
* #M115 "NK Cell/Gamma-Delta T Cell Lymphoma"
* #M116 "Hepatosplenic T Cell Lymphoma"
* #M117 "Histiocytosis"
* #M118 "Any patient undergoing Allogeneic Haematopoietic Stem Cell transplantation"
* #M120 "Atypical Teratoid/Rhabdoid Tumour"
* #M126 "CNS High-Grade Neuroepithelial Tumour with MN1 Alteration"
* #M130 "Cribriform Neuroepithelial Tumour"
* #M132 "Desmoplastic Infantile Gangliogliomas"
* #M133 "Desmoplastic Medulloblastoma"
* #M136 "Fibrolamellar Hepatocellular Carcinoma"
* #M137 "Ganglioglioma"
* #M138 "Glial Tumours"
* #M139 "Glioblastoma"
* #M145 "Medulloblastoma"
* #M146 "Medulloblastoma Group 3"
* #M147 "Medulloblastoma Group 3/4"
* #M148 "Medulloblastoma TP53 WT"
* #M150 "Meningioma"
* #M153 "Nodular Brain Tumour"
* #M155 "Oligoastrocytoma"
* #M156 "Oligodendroglioma"
* #M158 "Pilocytic Astrocytoma"
* #M159 "Pituitary Blastoma"
* #M160 "Pleomorphic Xanthoastrocytoma"
* #M162 "Primitive Neuroectodermal Tumours"
* #M168 "Rosette-Forming Glioneuronal Tumour"
* #M169 "Secondary Glioblastoma"
* #M170 "SHH Medulloblastoma"
* #M171 "SHH Medulloblastoma"
* #M172 "SHH Medulloblastoma"
* #M179 "WNT Medulloblastoma"
* #M181 "Hairy Cell Leukaemia"
* #M182 "ALK Positive Anaplastic Large Cell Lymphoma"
* #M183 "Diffuse Midline Glioma"
* #M184 "Glioma"
* #M185 "High Grade Glioma"
* #M186 "Low Grade Glioma"
* #M189 "Brain Tumour"
* #M190 "Embryonal Tumour Differential"
* #M191 "Low Grade Intrinsic Brain Tumour Differential"
* #M192 "High Grade Intrinsic Brain Tumour Differential"
* #M193 "Unable To Grade Intrinsic Brain Tumour"
* #M194 "Medulloblastoma all Subtypes"
* #M195 "Craniopharyngioma"
* #M213 "Glial and Glioneuronal Tumour Differential"
* #M224 "MDS/MPN"
* #M225 "Suspected Lymphoma"
* #M235 "Proven or Suspected Haematological Tumours Exhausted all Standard of Care Testing and Treatment"

// Retired - not in v9/v16, preserved from the existing fragment rather than dropped

* #R94 "Not present in 8.0"
* #R362 "Not present in 8.0"
