CodeSystem: NHSEngland-DigitalGenomicTestServices
Id: DigitalGenomicTestServices
Title: "NHS England Digital Genomic Test Services"
Description: """
The **digital** National Genomic Test Directory codes, rolled out as the
Test Directory itself went digital - replacing the legacy R-code/M-code
style codes in [NHS England Genomic Test
Code](CodeSystem-GenomicTestCode.html) (`$GTD`,
`England-GenomicTestDirectory`) for new/migrated indications. Two code
types share this one system, distinguished by prefix:

- **TP (Test Package)** codes replace the old clinical-indication concept -
  a package of related genomic tests grouped by clinical condition.
- **GT (Genomic/Genetic Test)** codes identify a single specific laboratory
  investigation.

Refreshed from the Haematological Oncology (v1.1) and Cancer CNS (v2) national
genomic test directories on 2026-09-05 - see `ConceptMap-GenomicTestCodeToDigitalGenomicTestServices`
and `ConceptMap-GenomicClinicalIndicationToDigitalGenomicTestServices` for how
these relate to the legacy codes they replace.
"""

* ^name = "DigitalGenomicTestServices"
* ^content = #fragment
* ^caseSensitive = true
* ^experimental = false
* ^status = #active
* ^version = "2026.09.05"
* ^date = "2026-09-05"
* ^url = "https://fhir.nhs.uk/CodeSystem/England-DigitalGenomicTestServices"

// Test Package (TP) - clinical-indication-level grouping

* #TP34 "Acute Lymphoblastic Leukaemia - T cell"
* #TP58 "Mature T Cell Neoplasms"
* #TP62 "Clonality Testing"
* #TP126 "Myeloma"
* #TP171 "Cystic renal disease"
* #TP182 "Histiocytosis"
* #TP202 "Myelodysplastic Syndromes"
* #TP228 "Myeloproliferative Neoplasm"
* #TP241 "Acute Lymphoblastic Leukaemia - B cell"
* #TP245 "Haematological Tumours - Exhausted SOC"
* #TP374 "Chronic Myeloid Leukaemia"
* #TP377 "Mature B Cell Neoplasms"
* #TP401 "Chimerism Testing"
* #TP450 "Acute Myeloid Leukaemia"
* #TP533 "Chronic Lymphocytic Leukaemia"
* #TP604 "Embryonal tumours of the CNS"
* #TP613 "Meningiomas"
* #TP622 "Tumours of the Sellar Region and Pituitary Tumours"
* #TP623 "Cranial and Paraspinal Nerve Tumours"
* #TP624 "Choroid Plexus Tumours"
* #TP625 "CNS of uncertain differentiation (NOS) and Rare Tumours"
* #TP640 "Gliomas, Glioneuronal Tumours, and Neuronal tumours"

// Genomic/Genetic Test (GT) - specific laboratory investigation

* #GT6 "Small variant (IDH2)"
* #GT7 "CRLF2, Xp22/Yp11 FISH - ALL"
* #GT10 "TAL1, 1p33 FISH - T-ALL"
* #GT12 "WGS Tumour First - Systemic mastocytosis"
* #GT13 "JAK2, 9q24 FISH - MPN"
* #GT14 "Chromosome 12 CNV FISH - AML"
* #GT17 "SNP Array - AML"
* #GT24 "WGS Tumour First - AML"
* #GT27 "MYC rearrangement FISH"
* #GT31 "MRD BCR::ABL1 - AML, ALL & CML"
* #GT35 "WGS Tumour First - Histiocytosis"
* #GT39 "T Cell Clonality Testing - Multiplex Sequencing"
* #GT40 "IGH::FGFR3, t(4;14)(p16;q32) FISH - Myeloma"
* #GT50 "Next Generation Sequencing RNA Panel - Structural Variants - Mature B Cell Neoplasms"
* #GT52 "JAK2, 9p24.1 FISH - ALL"
* #GT56 "IGH, 14q32 FISH - B-ALL"
* #GT59 "TCL1A, 14q32 FISH - Mature T Cell Neoplasms"
* #GT61 "DEK::NUP214, t(6;9)(p22;q34) FISH or RT-PCR - AML"
* #GT69 "BRAF Hotspot (V600E) High Sensitivity - Histiocytosis"
* #GT71 "Chromosome 19 CNV FISH - CML"
* #GT73 "Chromosome 7 CNV FISH - CML"
* #GT74 "NUP98::NSD1, t(5;11)(q35;p15.5) FISH - AML"
* #GT75 "Next Generation Sequencing Panel - Copy Number Variants - Myeloma"
* #GT85 "ABL1, 9q34 FISH - ALL"
* #GT88 "WGS Tumour First - exhausted SOC"
* #GT99 "Next Generation Sequencing Panel - Structural Variants - CML"
* #GT100 "SNP Array - MPN"
* #GT101 "RUNX1::RUNX1T1, t(8;21)(q22;q22) FISH or RT-PCR - AML"
* #GT104 "WGS Germline & Tumour - exhausted SOC"
* #GT112 "RBM15::MRTFA, t(1;22)(p13;q13) FISH - AML"
* #GT120 "MALT1, 18q21 FISH - Mature B Cell Neoplasms"
* #GT128 "WGS Follow-up Germline - MDS/MPN"
* #GT131 "BCOR CNV FISH"
* #GT133 "PML::RARA, t(15;17)(q24;q21) FISH or RT-PCR - AML"
* #GT147 "FGFR1, 8p11 FISH - MPN"
* #GT152 "ABL1, 9q34 FISH - MPN"
* #GT157 "GATA2::MECOM, inv(3)(q21q26) FISH - AML"
* #GT160 "Ploidy Status CNV FISH - ALL"
* #GT172 "MECOM, 3q21 FISH - MDS & MPN"
* #GT178 "SNP Array - Myeloma"
* #GT180 "NPM1::MLF1, t(3;5)(q25;q34) FISH - AML"
* #GT183 "WGS Germline & Tumour - T-ALL"
* #GT185 "Next Generation Sequencing Panel - Structural Variants - AML"
* #GT187 "IGH::CCND1, t(11;14)(q13;q32) FISH - Myeloma"
* #GT198 "Chromosome 7 CNV FISH - MDS & MPN"
* #GT200 "Other FISH Targets - ALL"
* #GT214 "Other MRD Targets - B-ALL"
* #GT217 "Genome-wide DNA Methylation Profiling"
* #GT225 "WGS Follow-up Germline - T-ALL"
* #GT231 "Chromosome 11 CNV FISH - CLL"
* #GT236 "BRAF rearrangement FISH"
* #GT237 "EWSR1 rearrangement FISH"
* #GT239 "TLX1::, 10q24 FISH - T-ALL"
* #GT246 "KIT Hotspot (D816) High Sensitivity - Systemic Mastocytosis"
* #GT253 "Next Generation Sequencing Panel - Small Variants - AML"
* #GT254 "WGS Tumour First - Acute leukaemia other"
* #GT256 "IRF4/DUSP22, 6p25 FISH - Mature T Cell Neoplasms"
* #GT258 "MLLT3::KMT2A, t(9;11)(p21;q23) & other KMT2A rearrangements FISH or RT-PCR - AML"
* #GT259 "Meningioma WGS - Paediatric and Adult"
* #GT265 "WGS Germline & Tumour - MDS/MPN"
* #GT267 "Next Generation Sequencing Panel - Small Variants - Mature B Cell Neoplasms"
* #GT272 "MYD88 Hotspot (L265P Variants) - Mature B Cell Neoplasms"
* #GT275 "CBFB::MYH11, inv(16)(p13.1q22) FISH or RT-PCR - AML"
* #GT279 "1p19q CNV FISH"
* #GT289 "CBFA2T3::GLIS2, inv(16)(p13.3q24.3) FISH - AML"
* #GT295 "SNP Array - B-ALL"
* #GT296 "ABL2, 1q25 FISH - ALL"
* #GT301 "KMT2A, 11q23 FISH - ALL"
* #GT303 "BCR::ABL1 TKD Variants - AML, ALL & CML"
* #GT304 "WGS Follow-up Germline - AA"
* #GT306 "Next Generation Sequencing Panel - Copy Number Variants - Mature B Cell Neoplasms"
* #GT312 "IGL::MYC, t(8;22)(q24;q11) FISH - Mature B Cell Neoplasms"
* #GT315 "TCF3, 19p13 FISH - ALL"
* #GT321 "BRAF Hotspot (V600E Variants) - Hairy Cell Leukaemia"
* #GT326 "MPL Hotspot (exon 10) - MPN"
* #GT329 "Next Generation Sequencing Panel - Structural Variants - ALL"
* #GT332 "MRD Target Identification - T-ALL"
* #GT338 "Chromosome 13 CNV FISH - CLL"
* #GT343 "MRD RUNX1::RUNX1T1 - AML"
* #GT345 "Chromosome 7 CNV FISH - Mature T Cell Neoplasms"
* #GT350 "Next Generation Sequencing Panel - Copy Number Variants - ALL"
* #GT351 "Other RT-PCR Targets - AML"
* #GT353 "CDKN2A CNV FISH"
* #GT355 "Chromosome 17 CNV FISH - MPN"
* #GT369 "IRF4, 6p25 FISH - Mature B Cell Neoplasms"
* #GT373 "PDGFRA, 4q21 FISH - MPN"
* #GT383 "Chromosome 17 CNV FISH - Myeloma"
* #GT386 "Next Generation Sequencing Panel - Structural Variants - MPN"
* #GT397 "Next Generation Sequencing Panel - Copy Number Variants - MDS"
* #GT414 "EZH2, 7q36 CNV FISH - Mature B Cell Neoplams"
* #GT426 "BRAF, 7q34 FISH - Histiocytosis"
* #GT429 "Next Generation Sequencing Panel - Small Variants - Myeloma"
* #GT431 "NTRK - Multi-target NGS panel - structural variants"
* #GT444 "SNP Array - Mature B Cell Neoplasms"
* #GT453 "RELA rearrangement FISH"
* #GT456 "NTRK1, 1q23 FISH - Histiocytosis"
* #GT467 "WGS Germline & Tumour - B-ALL"
* #GT468 "FIP1L1::PDGFRA, 4q12 FISH - MPN"
* #GT475 "MRD PML::RARA - AML"
* #GT478 "KMT2A, 11q23 FISH - CML"
* #GT479 "Chromosome 11q CNV FISH - B Cell Lymphoma with 11q Aberration"
* #GT483 "IGL::MYC, t(8;22)(q24;q11) FISH - ALL"
* #GT494 "IDH1 Hotspot (R132 Variants) - AML"
* #GT497 "Cystic renal disease - WGS"
* #GT508 "T Cell Clonality Testing - NGS"
* #GT512 "KMT2A::AFDN, t(6;11)(q27;q23) FISH - ALL"
* #GT517 "WGS Germline & Tumour - BPDCN"
* #GT527 "SNP Array - T-ALL"
* #GT533 "FLT3 ITD Targeted Assay - AML"
* #GT534 "REL, 2p16 CNV FISH - Mature B Cell Neoplasms"
* #GT538 "WGS Germline & Tumour - CML"
* #GT543 "WGS Tumour First - MPN"
* #GT546 "IGK::MYC, t(2;8)(p12;q24) FISH"
* #GT548 "ETV6::RUNX1, t(12;21)(p13;q22) & iAMP21 FISH - B-ALL"
* #GT549 "IGH::MAF, t(14;16)(q32;q23) FISH - Myeloma"
* #GT551 "IGHV Hypermutation (Multiplex Sequencing) - CLL"
* #GT552 "WGS Germline & Tumour - MPN"
* #GT565 "Other FISH Targets - Myeloma"
* #GT576 "MYC::IGH, t(8;14)(q34;q32) FISH - Mature B Cell Neoplasms"
* #GT577 "ETV6::RUNX1, t(12;21)(p13;q22) RT-PCR - ALL"
* #GT579 "ALK, 2p23 FISH - Histiocytosis"
* #GT583 "YAP1 rearrangement FISH"
* #GT592 "BRAF::KIAA1549 rearrangement"
* #GT593 "WGS Germline & Tumour - Histiocytosis"
* #GT595 "Chromosome 17 CNV FISH - MDS"
* #GT613 "BCL2, 18q21 FISH - Mature B Cell Neoplasms"
* #GT614 "Other RT-PCR Targets - MPN"
* #GT629 "Next Generation Sequencing Panel - Copy Number Variants - AML"
* #GT632 "MYC, 8q24 FISH - Myeloma"
* #GT634 "MYCN CNV FISH"
* #GT635 "SNP Array - MDS"
* #GT637 "CCND2, 12p13 FISH - Mantle Cell Lymphoma"
* #GT646 "IGH::BCL2, t(14;18)(q32;q21) FISH - Follicular Lymphoma"
* #GT649 "BCR::ABL1 multiplex - CML, ALL or AML"
* #GT656 "MNX1::ETV6, t(7;12)(q36;p13) FISH - AML"
* #GT662 "MRD FIP1L1::PDGFRA - MPN"
* #GT664 "IGK::MYC, t(2;8)(p12;q24) FISH - Mature B Cell Neoplasms"
* #GT665 "Other FISH Targets - Mature B Cell Neoplasms"
* #GT670 "WGS Germline & Tumour - Acute leukaemia other"
* #GT673 "MRD BCR::ABL1 Rare Transcripts - AML, ALL & CML"
* #GT687 "WGS Tumour First - T-ALL"
* #GT690 "MECOM, 3q21 FISH - CML"
* #GT694 "NUDT15, 13q14 Pharmacogenomic Test - ALL"
* #GT699 "FIP1L1::PDGFRA, 4q12 FISH or RT-PCR - MPN"
* #GT700 "Chromosome 7 CNV FISH - AML"
* #GT701 "Next Generation Sequencing Panel - Structural Variants - MDS"
* #GT702 "WGS Tumour First - JMML"
* #GT703 "Other MRD Targets - AML"
* #GT716 "Other FISH Targets - AML"
* #GT717 "Next Generation Sequencing Panel - Small Variants (Limited) - MPN"
* #GT720 "Neurological Tumours-EGFRvIII-RT-PCR"
* #GT723 "BCL6, 3q27 FISH - ALL"
* #GT725 "IGH, 14q32 FISH - Myeloma"
* #GT726 "WGS Germline & Tumour - AML"
* #GT729 "IGH::MYC, t(8;14)(q34;q32) FISH - ALL"
* #GT733 "TP63, 3q28 FISH - Mature T Cell Neoplasms"
* #GT736 "Next Generation Sequencing Panel - Copy Number Variants - MPN"
* #GT738 "MRD Target Identification - B-ALL"
* #GT739 "Other RT-PCR Targets - ALL"
* #GT746 "IGH::MAFB, t(14;20)(q32;q12) FISH - Myeloma"
* #GT756 "MYC, 8q24 FISH - ALL"
* #GT763 "BCR::ABL1, t(9;22)(q34;q11) FISH - MPN"
* #GT777 "BCOR rearrangement FISH"
* #GT778 "MYB rearrangement"
* #GT779 "BCL10, 1p22 FISH - Mature B Cell Neoplasms"
* #GT781 "WGS Tumour First - B-ALL"
* #GT790 "MYC CNV FISH"
* #GT795 "Next Generation Sequencing (DNA Based) Panel - Structural Variants - Mature B Cell Neoplasms"
* #GT802 "WGS Follow-up Germline - AML"
* #GT818 "PCM1::JAK2, t(8;9)(p22;q24) FISH - MPN"
* #GT819 "Next Generation Sequencing Panel - Small Variants - MPN"
* #GT821 "Next Generation Sequencing (DNA Based) Panel - Structural Variants - Mature T Cell Neoplasms"
* #GT825 "WGS Follow-up Germline - Acute Leukaemia Other"
* #GT836 "WGS Follow-up Germline - Histiocytosis"
* #GT844 "KMT2A::MLLT3, t(9;11)(p21;q23) FISH - ALL"
* #GT849 "Next Generation Sequencing Panel - Small Variants - ALL"
* #GT852 "IGH, 14q32 FISH - Mature B Cell Neoplasms"
* #GT854 "SNP Array"
* #GT855 "CKS1B, 1q21 & CDKN2C, 1p32 CNV FISH - Myeloma"
* #GT868 "CCND1, 11q13 FISH - Mantle Cell Lymphoma"
* #GT870 "MRD CBFB::MYH11 - AML"
* #GT874 "TCF3::PBX1, t(1;19)(q23;p13) & TCF3::HLF, t(17;19)(q22;p13) FISH - ALL"
* #GT879 "WGS Tumour First - BPDCN"
* #GT889 "WGS Tumour First - MDS/MPN"
* #GT890 "IGH::CCND3, t(6;14)(p21;q32) FISH - Myeloma"
* #GT892 "Next Generation Sequencing Panel - Small Variants - Histiocytosis"
* #GT913 "ALK rearrangement FISH"
* #GT914 "Next Generation Sequencing Panel - Structural Variants - Histiocytosis"
* #GT916 "FLT3 TKD Targeted Assay - AML"
* #GT918 "Karyotype - Mature B & T Cell Neoplasm"
* #GT921 "NPM1 Hotspot (exon 12) - AML"
* #GT923 "Chromosome 17 CNV FISH - CLL"
* #GT926 "Other FISH Targets - CLL"
* #GT929 "Next Generation Sequencing Panel - Copy Number Variants - CLL"
* #GT935 "SNP Array - CLL"
* #GT939 "Other FISH Targets - MDS"
* #GT943 "Embryonal Tumours WGS - Paediatric and Adult"
* #GT944 "MGMT promoter hypermethylation - methylation specific PCR"
* #GT965 "JAK2 Hotspot (exon 12) - MPN"
* #GT985 "Other MRD Targets - T-ALL"
* #GT986 "JAK2 Hotspot (V617F) - MPN"
* #GT999 "WGS Germline & Tumour - ALK Positive Anaplastic Large Cell Lymphoma"
* #GT1002 "WGS Follow-up Germline - ALK Positive Anaplastic Large Cell Lymphoma"
* #GT1007 "FOXP1, 3p13 FISH - Mature B Cell Neoplasms"
* #GT1008 "WGS Tumour First - ALK Positive Anaplastic Large Cell Lymphoma"
* #GT1012 "PTEN CNV FISH"
* #GT1015 "Chromosome 12 CNV FISH - MPN"
* #GT1023 "WGS Follow-up Germline - MDS"
* #GT1029 "WGS Follow-up Germline - Systemic Mastocytosis"
* #GT1033 "BCR::ABL1, t(9;22)(q34;q11) FISH - AML"
* #GT1034 "Chromosome 8 CNV FISH - CML"
* #GT1042 "CALR Hotspot (exon 9) - MPN"
* #GT1049 "EGFR CNV FISH"
* #GT1050 "WGS Follow-up Germline - B-ALL"
* #GT1052 "BCL2, 18q21 FISH - ALL"
* #GT1062 "MRD NPM1 - AML"
* #GT1063 "WGS Germline & Tumour - Systemic mastocytosis"
* #GT1064 "Chromosome 17 CNV FISH - AML"
* #GT1076 "WGS Follow-up Germline - exhausted SOC"
* #GT1089 "PDGFRA, 4q12 FISH - ALL"
* #GT1096 "Karyotype - AML, ALL & CML"
* #GT1114 "WGS Follow-up Germline - JMML"
* #GT1129 "CDKN2B CNV FISH"
* #GT1138 "MYBL1 rearrangement"
* #GT1146 "TCR FISH - Mature T Cell Neoplasms"
* #GT1149 "MRD Quantification - T-ALL"
* #GT1153 "Next Generation Sequencing RNA Panel - Structural Variants - Mature T Cell Neoplasms"
* #GT1163 "BCR::ABL1, t(9;22)(q34;q11) FISH - ALL"
* #GT1166 "NUP98, 11p15 FISH - AML"
* #GT1180 "PDGFRB / CSF1R, 5q32 FISH - ALL"
* #GT1181 "IGHV Hypermutation (NGS) - CLL"
* #GT1185 "TPMT, 6p22 Pharmacogenomic Test - ALL"
* #GT1191 "KMT2A::AFF1, t(4;11)(q21;q23) FISH - ALL"
* #GT1193 "Other FISH Targets - CML"
* #GT1209 "Next Generation Sequencing Panel - Small Variants - CLL"
* #GT1211 "Other FISH Targets - MPN"
* #GT1221 "WGS Follow-up Germline - BPDCN"
* #GT1224 "Chromosome 5 CNV FISH - MDS & MPN"
* #GT1228 "MRD NPM1 Rare Transcripts - AML"
* #GT1233 "Karyotype - MPN"
* #GT1236 "WGS Follow-up Germline - MPN"
* #GT1238 "WGS Germline & Tumour - JMML"
* #GT1247 "MRD Quantification - B-ALL"
* #GT1248 "Chromosome 8 CNV FISH - MDS & MPN"
* #GT1253 "IGHV hypermutation (Multiplex Sequencing) - Hairy Cell Leukaemia"
* #GT1258 "TP53 deletion CNV FISH"
* #GT1260 "Ependymal Tumours Differential Diagnosis-NGS Panel SNV and CNV"
* #GT1265 "SNP Array - CML"
* #GT1274 "Next Generation Sequencing Panel - Structural Variants - Myeloma"
* #GT1277 "Hyperdiploidy CNV FISH or MLPA - Myeloma"
* #GT1279 "Next Generation Sequencing Panel - Small Variants - Mature T Cell Neoplasms"
* #GT1280 "MN1 rearrangement"
* #GT1281 "Chromosome 12 CNV FISH - CLL"
* #GT1282 "ETV6::PDGFRB, t(5;12)(q33;p13) FISH - MPN"
* #GT1285 "BCL6, 3q27 FISH - Mature B Cell Neoplasms"
* #GT1294 "Chromosome 5 CNV FISH - AML"
* #GT1297 "Next Generation Sequencing Panel - Small Variants - MDS"
* #GT1300 "KMT2A::ELL, t(11;19)(q23;p13.1) FISH - ALL"
* #GT1302 "Chromosome 20 CNV FISH - MDS"
* #GT1308 "KMT2A::MLLT10, t(10;11)(p12;q23) FISH - ALL"
* #GT1309 "KMT2A::MLLT1, t(11;19)(q23;p13.3) FISH - ALL"
* #GT1312 "WGS Germline & Tumour - MDS"
* #GT1317 "Small variant (IDH1)"
* #GT1332 "ZFTA rearrangements FISH"
* #GT1333 "Structural variant, not otherwise specified - Targeted Variant Test"
* #GT1334 "Small nucleotide variant , not otherwise specified - Targeted Variant Test"
* #GT1335 "Chimerism by STR Testing - Post Solid Organ Transplant"
* #GT1336 "Chimerism by XY FISH - Post Solid Organ Transplant"
* #GT1337 "CD79B Hotspot (Y196 Variants) - Mature B Cell Neoplasms"
* #GT1338 "Other FISH Targets - Mature T cell neoplasms"
* #GT1339 "WGS Germline & Tumour - B Cell Lymphoma with 11q Aberration"
* #GT1340 "WGS Tumour First - AA"
* #GT1341 "WGS Germline & Tumour - B Cell Lymphoma with IRF4 Rearrangement"
* #GT1342 "WGS Germline & Tumour - Follicular Lymphoma"
* #GT1343 "WGS Follow-up Germline - Follicular lymphoma"
* #GT1344 "WGS Germline & Tumour - Marginal Zone Lymphoma"
* #GT1345 "Chromosome 17 CNV FISH - CML"
* #GT1346 "Copy number variant, not otherwise specified - Targeted Variant Test"
* #GT1347 "WGS Germline & Tumour - High Grade Lymphoma"
* #GT1348 "CIITA, 16p13 FISH - Mature B Cell Neoplasms"
* #GT1349 "WGS Tumour First - Burkitt Lymphoma"
* #GT1350 "WGS Germline & Tumour - Burkitt Lymphoma"
* #GT1351 "WGS Follow-up Germline - High Grade Lymphoma"
* #GT1352 "WGS Germline & Tumour - Hepatosplenic T Cell Lymphoma"
* #GT1353 "WGS Follow-up Germline - T Cell NHL"
* #GT1354 "ALK, 2p23 FISH - Mature B Cell Neoplasms"
* #GT1355 "PDGFRB, 5q32 FISH - MPN"
* #GT1356 "WGS Germline & Tumour - Low Grade Lymphoma"
* #GT1357 "WGS Follow-up Germline - CML"
* #GT1358 "WGS Tumour First - T Cell NHL"
* #GT1359 "WGS Follow-up Germline - ALK Negative Anaplastic Large Cell Lymphoma"
* #GT1360 "WGS Tumour First - ALK Positive Large B Cell Lymphoma"
* #GT1361 "WGS Tumour First - Hepatosplenic T Cell Lymphoma"
* #GT1362 "WGS Tumour First - ALK Negative Anaplastic Large Cell Lymphoma"
* #GT1363 "WGS Follow-up Germline - B Cell Lymphoma with 11q Aberration"
* #GT1364 "WGS Follow-up Germline - Hepatosplenic T Cell Lymphoma"
* #GT1365 "WGS Follow-up Germline - Marginal Zone Lymphoma"
* #GT1366 "WGS Follow-up Germline - Low Grade Lymphoma"
* #GT1367 "WGS Follow-up Germline - B Cell Lymphoma with IRF4 Rearrangement"
* #GT1368 "Chimerism by STR Testing - Post Stem Cell Transplant"
* #GT1369 "WGS Germline & Tumour - ALK Negative Anaplastic Large Cell Lymphoma"
* #GT1370 "Chimerism by XY FISH - Post Stem Cell Transplant"
* #GT1371 "BCR::ABL1, t(9;22)(q34;q11) FISH - CML"
* #GT1372 "WGS Follow-up Germline - NK Cell/Gamma-Delta T Cell Lymphoma"
* #GT1373 "WGS Tumour First - CML"
* #GT1375 "Karyotype - MDS"
* #GT1376 "WGS Germline & Tumour - NK Cell/Gamma-Delta T Cell Lymphoma"
* #GT1377 "WGS Tumour First - Low Grade Lymphoma"
* #GT1378 "WGS Germline & Tumour - ALK Positive Large B Cell Lymphoma"
* #GT1379 "WGS Tumour First - Follicular Lymphoma"
* #GT1380 "IGHV Hypermutation (NGS) - Hairy Cell Leukaemia"
* #GT1381 "WGS Germline & Tumour - Primary Mediastinal B Cell Lymphoma"
* #GT1382 "WGS Germline & Tumour - AA"
* #GT1383 "WGS Follow-up Germline - ALK Positive Large B Cell Lymphoma"
* #GT1384 "WGS Tumour First - NK Cell/Gamma-Delta T Cell Lymphoma"
* #GT1385 "ALK::NPM1, t(2;5)(p23;q35) FISH - Mature T Cell Neoplasms"
* #GT1386 "WGS Germline & Tumour - T Cell NHL"
* #GT1387 "WGS Follow-up Germline - Primary Mediastinal B Cell Lymphoma"
* #GT1388 "WGS Follow-up Germline - Burkitt Lymphoma"
* #GT1389 "WGS Tumour First - Marginal Zone Lymphoma"
* #GT1390 "WGS Tumour First - B Cell Lymphoma with 11q Aberration"
* #GT1391 "WGS Tumour First - Primary Mediastinal B Cell Lymphoma"
* #GT1392 "WGS Tumour First - B Cell Lymphoma with IRF4 Rearrangement"
* #GT1393 "WGS Tumour First - High Grade Lymphoma"
* #GT1394 "MYC, 8q24 FISH - Mature B Cell Neoplasms"
* #GT1403 "Gliomas, Glioneuronal Tumours, and Neuronal tumours Differential Diagnosis-NGS Panel SNV and CNV"
* #GT1404 "CD274 / PDCD1LG2, 9p24 FISH - Mature B Cell Neoplasms"
* #GT1405 "Tumours of the Sellar Region and Pituitary Tumours Differential Diagnosis-NGS Panel SNV and CNV"
* #GT1407 "IGH::CCND1, t(11;14)(q13;q32) FISH - Mantle Cell Lymphoma"
* #GT1408 "B Cell Clonality Testing - NGS"
* #GT1411 "Embryonal Tumours Differential Diagnosis-NGS Panel SNV and CNV"
* #GT1413 "Embryonal Tumours Differential Diagnosis-NGS Panel Structural Variant"
* #GT1414 "Next Generation Sequencing Panel - Copy Number Variant - CML"
* #GT1415 "Gliomas, Glioneuronal Tumours, and Neuronal tumours Differential Diagnosis-NGS Panel Structural Variants"
* #GT1416 "ALK, 2p23 FISH - Mature T Cell Neoplasms"
* #GT1418 "Ependymal Tumours Differential Diagnosis-NGS Panel Structural Variants"
* #GT1420 "Meningiomas Differential Diagnosis-NGS Panel SNV and CNV"
* #GT1422 "Chromosome 8 CNV FISH - Mature T Cell Neoplasms"
* #GT1423 "B Cell Clonality Testing - Multiplex Sequencing"
* #GT1424 "Chromosome 5 CNV FISH - CML"
* #GT1426 "Next Generation Sequencing Panel - Small Variant - CML"
* #GT1427 "Choroid plexus tumours - NGS Panel SNV and CNV"
* #GT1428 "Choroid plexus tumours WGS - Paediatric and Adult"
* #GT1429 "Tumours of the CNS NOS including Rare tumours Differential Diagnosis-NGS Panel SNV and CNV"
* #GT1430 "Tumours of the CNS NOS including Rare tumours Differential Diagnosis-NGS Panel Structural Variant"
* #GT1431 "CNS of uncertain differentiation (NOS) and Rare Tumours WGS - Paediatric and Adult"
* #GT1432 "Gliomas, Glioneuronal Tumours, and Neuronal tumours WGS - Paediatric and Adult"
* #GT1433 "Tumours of the Sellar Region and Pituitary Tumours WGS - Paediatric and Adult"
* #GT1434 "Cranial and paraspinal nerve tumours Differential - NGS Panel SNV and CNV"
* #GT1435 "Cranial and paraspinal nerve tumours Differential - NGS Panel Structural Variant"
* #GT1436 "Cranial and paraspinal nerve tumours WGS- Paediatric and Adult"
* #GT1439 "WGS Tumour First - MDS"
* #GT1497 "MRD JAK2 Hotspot (V617F) - MPN"
